/**
 * The migration journal — the index that says which snapshot belongs to which
 * migration file, and in what order they apply. Same shape drizzle-kit uses,
 * so a history generated by either tool is readable by the other.
 */
export interface JournalEntry {
	readonly idx: number;
	readonly version: string;
	readonly when: number;
	readonly tag: string;
	readonly breakpoints: boolean;
}

export interface Journal {
	readonly version: string;
	readonly dialect: 'sqlite';
	readonly entries: readonly JournalEntry[];
}

export const emptyJournal = (): Journal => ({ version: '7', dialect: 'sqlite', entries: [] });

export const nextIndex = (journal: Journal): number =>
	journal.entries.reduce((max, entry) => Math.max(max, entry.idx + 1), 0);

/**
 * What a migration name may contain.
 *
 * The name becomes the tag, and the tag becomes a **path**: `writeMigration`
 * joins it onto the output folder and `readMigration` joins it back. An
 * unvalidated `--name ../../../tmp/pwned` produced the tag
 * `0003_../../../tmp/pwned` and wrote outside the migrations folder entirely.
 * The name is usually hand-typed, which is why this went unnoticed — but a CI
 * job deriving `--name` from a branch or PR title is exactly the case where
 * nobody is reading it.
 *
 * Checked here rather than at the flag, because `generate` and `pull` both
 * build a tag and both take `--name`; this is the one place they share.
 */
const VALID_MIGRATION_NAME = /^[A-Za-z0-9_-]+$/;

/** `0003_lively_moon` — the wrangler-compatible file naming. */
export const migrationTag = (index: number, name: string): string => {
	if (!VALID_MIGRATION_NAME.test(name)) {
		throw new Error(
			`Invalid migration name ${JSON.stringify(name)}. It becomes the migration's file name, so it may `
				+ 'contain only letters, digits, underscores and hyphens — no path separators, dots or spaces.',
		);
	}
	return `${String(index).padStart(4, '0')}_${name}`;
};

export const appendEntry = (journal: Journal, tag: string, when: number): Journal => ({
	...journal,
	entries: [
		...journal.entries,
		{ idx: nextIndex(journal), version: '7', when, tag, breakpoints: true },
	],
});

/** Which journal entries have not been recorded in the database yet. */
export const pendingMigrations = (journal: Journal, applied: readonly string[]): JournalEntry[] => {
	const seen = new Set(applied.map((name) => name.replace(/\.sql$/, '')));
	return journal.entries.filter((entry) => !seen.has(entry.tag)).sort((a, b) => a.idx - b.idx);
};

const ADJECTIVES = [
	'brave', 'calm', 'clever', 'curious', 'eager', 'gentle', 'jolly', 'lively',
	'lucky', 'mellow', 'nimble', 'plucky', 'quiet', 'silent', 'spry', 'sunny',
];

const NOUNS = [
	'anchor', 'atlas', 'beacon', 'canyon', 'comet', 'delta', 'ember', 'harbor',
	'lagoon', 'meadow', 'moon', 'orbit', 'pebble', 'summit', 'thicket', 'willow',
];

/**
 * A stable, readable name derived from the index — deterministic, so
 * regenerating the same migration produces the same file name.
 */
export const migrationName = (index: number): string =>
	`${ADJECTIVES[index % ADJECTIVES.length]!}_${NOUNS[(index * 7) % NOUNS.length]!}`;
