/**
 * The snapshot: a normalised JSON description of a schema.
 *
 * Migrations are generated by diffing two of these, so the format is the
 * contract between `generate`, `pull` and `check`. It deliberately mirrors
 * drizzle-kit's shape — it is a reasonable design, and matching it is what
 * makes importing an existing migration history possible.
 */
import { createIndex, createTable, defaultExpression, foreignKeyName, literal, renderInline, uniqueConstraintName } from 'orm-d1/ddl';
import type { TableOptionsMap } from 'orm-d1/ddl';
import { appendOnlyKey, assertAppendOnlyColumns } from 'orm-d1/ddl';
import type { Column, Table } from 'orm-d1';
import { getTableColumns, getTableExtras, getTableName, isColumn } from 'orm-d1';

/**
 * What a table's `appendOnly` option becomes in the snapshot.
 *
 * The column list is validated here as well as in `createSchema`, because the
 * snapshot is written by `generate` before any DDL is rendered: without this a
 * typo'd column name would be recorded as the guard, and SQLite accepts such a
 * trigger silently (see `assertAppendOnlyColumns`).
 */
const appendOnlySnapshotValue = (
	t: Table,
	value: boolean | readonly string[] | undefined,
): boolean | readonly string[] => {
	if (!value) return false;
	if (value === true) return true;
	return assertAppendOnlyColumns(t, value);
};

/**
 * `2` added `strict`, `withoutRowid` and `appendOnly` to `TableSnapshot`.
 * `3` widened `appendOnly` from `boolean` to `boolean | string[]`.
 *
 * A version-1 snapshot simply lacks the three fields, and they read as `false`,
 * which is exactly what a database written before they existed looks like. A
 * version-2 snapshot only ever holds `true` or `false`, which version 3 still
 * reads unchanged. So both bumps are for diagnostics and `up`, not for
 * correctness of the read path.
 */
export const SNAPSHOT_VERSION = '3';

export interface ColumnSnapshot {
	readonly name: string;
	readonly type: string;
	/**
	 * The exact string a `customType`'s `dataType(config)` declared, when this
	 * column has one — `orm-d1/ddl`'s `typeName()` emits this verbatim instead
	 * of `type` (which is only ever a reduced SQLite storage-class affinity).
	 * Absent on a snapshot written before this field existed, and absent for
	 * every non-`customType` column; both read as "no declared type", i.e. fall
	 * back to `type`. Comparison (`canonicalTable`) deliberately does not look
	 * at this — it stays affinity-based so a live D1 column's spelling never
	 * causes a spurious diff — only DDL *emission* needs the exact string.
	 */
	readonly declaredType?: string | undefined;
	readonly primaryKey: boolean;
	readonly notNull: boolean;
	readonly autoincrement: boolean;
	readonly unique: boolean;
	/** SQL text of the default, already literalised. `undefined` = no default. */
	readonly default?: string | undefined;
	readonly generated?: { readonly as: string; readonly mode: 'stored' | 'virtual' } | undefined;
	/** A column-level foreign key. Table-level ones live in `foreignKeys`. */
	readonly references?: ForeignKeySnapshot | undefined;
	/**
	 * The column's own `COLLATE` clause, in whatever case the DDL text used.
	 * `undefined` means "not stated" — which is also what a schema-derived
	 * snapshot always has, since Drizzle (and so orm-d1) has no `.collate()`
	 * spelling. `undefined` and an explicit `binary` are equivalent (BINARY is
	 * SQLite's default), but `undefined` against any *other* live collation
	 * (e.g. `nocase`) is a real, reportable difference — see `canonicalTable`.
	 */
	readonly collate?: string | undefined;
}

/**
 * One member of an index's column list.
 *
 * `isExpression: true` means `expression` is a SQL fragment (e.g.
 * `lower("email")` from `index(...).on(sql\`lower(${t.email})\`)`), not a bare
 * identifier — `createIndexFromSnapshot` must not quote it as one, or the
 * index binds to a constant string literal instead of the expression.
 *
 * A snapshot written before this shape existed has plain strings in
 * `columns` instead of `IndexColumnSnapshot` objects; every reader normalises
 * a bare string to `{ expression: <string>, isExpression: false }` — see
 * `normalizeIndexColumn`.
 */
export interface IndexColumnSnapshot {
	readonly expression: string;
	readonly isExpression: boolean;
	/** `DESC` in the index's column list. Absent/`false` means ascending, SQLite's default. */
	readonly desc?: boolean;
	/**
	 * An explicit `COLLATE <name>` on this index member. Absent means the
	 * column's own declared collation (or `BINARY`) applies — SQLite reports
	 * every member's collation, including the implicit default, so this is
	 * only set when it differs from `BINARY`, the default for an unqualified
	 * column, to keep an ordinary index from growing a spurious `collate`.
	 */
	readonly collate?: string;
}

/**
 * Reads either shape a `columns` entry can be on disk: the current
 * `IndexColumnSnapshot`, or a bare string from a pre-upgrade snapshot (always
 * an identifier, so `isExpression: false`).
 */
export const normalizeIndexColumn = (entry: string | IndexColumnSnapshot): IndexColumnSnapshot =>
	typeof entry === 'string' ? { expression: entry, isExpression: false } : entry;

/**
 * Drizzle's `IndexColumn` (`SQLiteColumn | SQL`, `drizzle-orm/sqlite-core`)
 * has no `.desc()`/`.collate()` on the column builder — there is no
 * first-class spelling for a DESC or COLLATE index member, only the raw-SQL
 * escape hatch already used for an expression index. A schema author states
 * one as `sql\`"col" collate NOCASE desc\``, which arrives here as an opaque
 * expression string identical in shape to `sql\`lower("col")\`` — but it
 * isn't one: it is a plain column, decorated, and `pragma index_xinfo`
 * reports it as exactly that (`cid` pointing at the real column, `desc`/`coll`
 * set), not as an expression member (`cid: -2`). Left undecomposed, a
 * schema-declared DESC/COLLATE index would permanently diff against the
 * database it exactly describes. So a raw-SQL member that is nothing but a
 * quoted identifier plus an optional `collate <name>` and/or `desc`/`asc` is
 * parsed back into the same structured shape introspection produces —
 * mirroring `parseIndexColumns`, which does the same job in the other
 * direction for expression members.
 */
const decorateIndexColumn = (raw: string): IndexColumnSnapshot => {
	const match = raw.trim().match(
		/^"((?:[^"]|"")+)"(?:\s+collate\s+(\w+))?(?:\s+(asc|desc))?$/i,
	);
	if (!match) return { expression: raw, isExpression: true };
	const [, name, collate, order] = match;
	return {
		expression: (name ?? '').replaceAll('""', '"'),
		isExpression: false,
		...(order?.toLowerCase() === 'desc' ? { desc: true } : {}),
		// Folded the same way `canonicalIndex` (diff.ts) folds the
		// introspected side, so `collate NOCASE` here and `collate NoCase`
		// read back from a live DB's DDL compare equal instead of spuriously
		// diffing on case alone.
		...(collate && collate.toLowerCase() !== 'binary' ? { collate: collate.toLowerCase() } : {}),
	};
};

export interface IndexSnapshot {
	readonly name: string;
	readonly columns: readonly (string | IndexColumnSnapshot)[];
	readonly isUnique: boolean;
	readonly where?: string | undefined;
}

export interface ForeignKeySnapshot {
	readonly name: string;
	readonly columns: readonly string[];
	readonly tableTo: string;
	readonly columnsTo: readonly string[];
	readonly onDelete?: string | undefined;
	readonly onUpdate?: string | undefined;
}

export interface TableSnapshot {
	readonly name: string;
	readonly columns: Record<string, ColumnSnapshot>;
	readonly indexes: Record<string, IndexSnapshot>;
	readonly foreignKeys: Record<string, ForeignKeySnapshot>;
	readonly compositePrimaryKeys: Record<string, { name: string; columns: readonly string[] }>;
	readonly uniqueConstraints: Record<string, { name: string; columns: readonly string[] }>;
	readonly checkConstraints: Record<string, { name: string; value: string }>;
	/**
	 * Physical-storage options and the append-only guard, from the sidecar
	 * `tableOptions()` module (see `orm-d1/ddl`). Optional so a version-1
	 * snapshot still parses; absent means `false`.
	 *
	 * `strict` and `withoutRowid` are properties of the `CREATE TABLE` itself, so
	 * changing either forces a full table rebuild. `appendOnly` is a separate
	 * trigger object, so it can be added or dropped in place — but it *is*
	 * dropped along with the table, so a rebuild has to re-emit it.
	 *
	 * `appendOnly` is `true` for a whole-table guard, or the list of columns a
	 * column-scoped guard covers. Narrowing or widening that list is also a
	 * trigger-only change.
	 */
	readonly strict?: boolean;
	readonly withoutRowid?: boolean;
	readonly appendOnly?: boolean | readonly string[];
}

export interface Snapshot {
	readonly version: string;
	readonly dialect: 'sqlite';
	readonly id: string;
	readonly prevId: string;
	readonly tables: Record<string, TableSnapshot>;
	/**
	 * Where this snapshot came from. Only a schema-derived one knows the
	 * declared name of a unique, check or foreign-key constraint — SQLite does
	 * not store them, so an introspected snapshot carries whatever the engine
	 * made up (`sqlite_autoindex_users_1`). Anything that reasons about names
	 * has to check this first, or it reports a rename between every pair of
	 * snapshots that did not come from the same side. Absent on snapshots
	 * written before this field existed, which is treated as unknown.
	 */
	readonly origin?: 'schema' | 'introspection';
}

export const emptySnapshot = (id = '0'.repeat(8), prevId = ''): Snapshot => ({
	version: SNAPSHOT_VERSION,
	dialect: 'sqlite',
	id,
	prevId,
	tables: {},
	// It has no constraints to have names for, so it agrees with either side.
	origin: 'schema',
});

const defaultOf = (column: Column<any>): string | undefined => {
	const value = column.config.default;
	if (!value) return undefined;
	return value.kind === 'sql'
		? defaultExpression(renderInline(value.value as never))
		: literal(column.config.encode(value.value));
};

const columnSnapshot = (column: Column<any>): ColumnSnapshot => ({
	name: column.name,
	type: column.config.type,
	declaredType: column.config.declaredType,
	primaryKey: column.config.primaryKey,
	notNull: column.config.notNull,
	autoincrement: column.config.autoIncrement,
	unique: column.config.unique,
	default: defaultOf(column),
	generated: column.config.generated
		? { as: renderInline(column.config.generated.as), mode: column.config.generated.mode }
		: undefined,
	references: column.config.references
		? {
			name: `${column.tableName}_${column.name}_fk`,
			columns: [column.name],
			tableTo: column.config.references.ref().tableName,
			columnsTo: [column.config.references.ref().name],
			onDelete: column.config.references.onDelete,
			onUpdate: column.config.references.onUpdate,
		}
		: undefined,
});

/**
 * Build a snapshot from live schema objects.
 *
 * `options` is the sidecar `tableOptions()` map. It is separate from the schema
 * module because `STRICT` / `WITHOUT ROWID` / triggers have no spelling in
 * `drizzle-orm/sqlite-core`, and docs/04 keeps the schema DSL a strict subset of
 * it — see the `TableOptions` docs in `orm-d1/ddl`.
 */
export function snapshotFromSchema(
	schema: Record<string, unknown> | readonly Table[],
	id = '',
	options?: TableOptionsMap | undefined,
): Snapshot {
	const tables = Array.isArray(schema)
		? (schema as readonly Table[])
		: Object.values(schema as Record<string, unknown>).filter(isTableLike);

	const result: Record<string, TableSnapshot> = {};

	for (const t of tables) {
		const name = getTableName(t);
		const columns: Record<string, ColumnSnapshot> = {};
		for (const column of Object.values(getTableColumns(t)) as Column<any>[]) {
			columns[column.name] = columnSnapshot(column);
		}

		// `Object.create(null)`, not `{}`: a constraint's derived or explicit name
		// is attacker- or DB-controlled text (`pull` on a foreign database emits
		// whatever names it finds), and a plain object literal treats a name like
		// `constructor` or `__proto__` specially — the former reads back an
		// inherited function instead of `undefined`, so the collision check below
		// would misfire on a name that was never actually used, and the latter
		// silently sets the object's prototype instead of adding an entry,
		// dropping the constraint with no error at all. A null-prototype object
		// has no inherited keys and no `__proto__` accessor, so every name is
		// just data.
		const indexes: Record<string, IndexSnapshot> = Object.create(null);
		const foreignKeys: Record<string, ForeignKeySnapshot> = Object.create(null);
		const compositePrimaryKeys: Record<string, { name: string; columns: readonly string[] }> = Object.create(null);
		const uniqueConstraints: Record<string, { name: string; columns: readonly string[] }> = Object.create(null);
		const checkConstraints: Record<string, { name: string; value: string }> = Object.create(null);

		for (const extra of getTableExtras(t)) {
			switch (extra.kind) {
				case 'index': {
					// Reuse the DDL generator's naming, so a generated migration
					// and a `createSchema()` call cannot disagree.
					const statement = createIndex(extra.meta, name);
					const indexName = statement.match(/index (?:if not exists )?"((?:[^"]|"")+)"/)?.[1]
						?.replaceAll('""', '"') ?? '';
					if (Object.hasOwn(indexes, indexName)) {
						const columns = extra.meta.columns.map((c) =>
							isColumn(c) ? c.name : renderInline(c as never)
						).join(', ');
						throw new Error(
							`"${name}" declares two indexes that both derive the name "${indexName}" `
								+ `(the second is on "${columns}"). `
								+ 'Give at least one an explicit name — an unnamed expression index is named "expr" '
								+ 'whatever the expression is, so the second would silently replace the first.',
						);
					}
					indexes[indexName] = {
						name: indexName,
						columns: extra.meta.columns.map((c) =>
							isColumn(c)
								? { expression: c.name, isExpression: false }
								: decorateIndexColumn(renderInline(c as never))
						),
						isUnique: extra.meta.unique,
						where: extra.meta.where ? renderInline(extra.meta.where) : undefined,
					};
					break;
				}
				case 'primaryKey': {
					const pkName = extra.meta.name ?? `${name}_pk`;
					if (Object.hasOwn(compositePrimaryKeys, pkName)) {
						const columns = extra.meta.columns.map((c) => c.name).join(', ');
						throw new Error(
							`"${name}" declares two primary keys that both derive the name "${pkName}" `
								+ `(the second is on "${columns}"). `
								+ 'Give at least one an explicit name.',
						);
					}
					compositePrimaryKeys[pkName] = {
						name: pkName,
						columns: extra.meta.columns.map((c) => c.name),
					};
					break;
				}
				case 'unique': {
					const uqName = uniqueConstraintName(extra.meta, name);
					if (Object.hasOwn(uniqueConstraints, uqName)) {
						const columns = extra.meta.columns.map((c) => c.name).join(', ');
						throw new Error(
							`"${name}" declares two unique constraints that both derive the name "${uqName}" `
								+ `(the second is on "${columns}"). `
								+ 'Give at least one an explicit name.',
						);
					}
					uniqueConstraints[uqName] = { name: uqName, columns: extra.meta.columns.map((c) => c.name) };
					break;
				}
				case 'foreignKey': {
					// The derivation is imported, not restated: the snapshot keys
					// foreign keys by this name, so a spelling that differs from the
					// DDL's — or that omits the columns, as this one did — loses a
					// constraint to a collision between two unnamed keys.
					const fkName = foreignKeyName(extra.meta, name);
					if (Object.hasOwn(foreignKeys, fkName)) {
						const columns = extra.meta.columns.map((c) => c.name).join(', ');
						throw new Error(
							`"${name}" declares two foreign keys that both derive the name "${fkName}" `
								+ `(the second is on "${columns}"). `
								+ 'Give at least one an explicit name.',
						);
					}
					foreignKeys[fkName] = {
						name: fkName,
						columns: extra.meta.columns.map((c) => c.name),
						tableTo: extra.meta.foreignColumns[0]?.tableName ?? '',
						columnsTo: extra.meta.foreignColumns.map((c) => c.name),
						onDelete: extra.meta.onDelete,
						onUpdate: extra.meta.onUpdate,
					};
					break;
				}
				case 'check': {
					if (Object.hasOwn(checkConstraints, extra.meta.name)) {
						const value = renderInline(extra.meta.value);
						throw new Error(
							`"${name}" declares two check constraints both named "${extra.meta.name}" `
								+ `(the second is "${value}"). `
								+ 'Rename one — check() requires an explicit name, so both already have one.',
						);
					}
					checkConstraints[extra.meta.name] = {
						name: extra.meta.name,
						value: renderInline(extra.meta.value),
					};
					break;
				}
			}
		}

		const perTable = options?.byTable[name];
		result[name] = {
			name,
			columns,
			indexes,
			foreignKeys,
			compositePrimaryKeys,
			uniqueConstraints,
			checkConstraints,
			strict: perTable?.strict ?? false,
			withoutRowid: perTable?.withoutRowid ?? false,
			appendOnly: appendOnlySnapshotValue(t, perTable?.appendOnly),
		};
	}

	return { version: SNAPSHOT_VERSION, dialect: 'sqlite', id, prevId: '', tables: result, origin: 'schema' };
}

const isTableLike = (value: unknown): value is Table =>
	typeof value === 'object' && value !== null
	&& Symbol.for('ormD1:IsTable') in (value as Record<symbol, unknown>);

/** The `CREATE TABLE` a snapshot table implies, without needing live objects. */
export function createTableFromSnapshot(t: TableSnapshot): string {
	const quote = (name: string): string => `"${name.replaceAll('"', '""')}"`;
	const hasCompositePk = Object.keys(t.compositePrimaryKeys).length > 0;
	const parts: string[] = [];

	for (const column of Object.values(t.columns)) {
		let ddl = `${quote(column.name)} ${column.declaredType ?? column.type}`;
		if (column.collate) ddl += ` collate ${column.collate}`;
		if (!hasCompositePk && column.primaryKey) {
			ddl += ' primary key';
			if (column.autoincrement) ddl += ' autoincrement';
		}
		if (column.notNull) ddl += ' not null';
		if (column.unique) ddl += ' unique';
		if (column.generated) ddl += ` generated always as (${column.generated.as}) ${column.generated.mode}`;
		if (column.default !== undefined) ddl += ` default ${column.default}`;
		if (column.references) ddl += referenceClause(column.references, quote);
		parts.push(ddl);
	}

	for (const pk of Object.values(t.compositePrimaryKeys)) {
		parts.push(`constraint ${quote(pk.name)} primary key (${pk.columns.map(quote).join(', ')})`);
	}
	for (const uq of Object.values(t.uniqueConstraints)) {
		parts.push(`constraint ${quote(uq.name)} unique (${uq.columns.map(quote).join(', ')})`);
	}
	for (const fk of Object.values(t.foreignKeys)) {
		parts.push(
			`constraint ${quote(fk.name)} foreign key (${fk.columns.map(quote).join(', ')})`
				+ ` references ${quote(fk.tableTo)}(${fk.columnsTo.map(quote).join(', ')})`
				+ (fk.onDelete ? ` on delete ${fk.onDelete}` : '')
				+ (fk.onUpdate ? ` on update ${fk.onUpdate}` : ''),
		);
	}
	for (const check of Object.values(t.checkConstraints)) {
		parts.push(`constraint ${quote(check.name)} check (${check.value})`);
	}

	// Same order as `createTable` in `orm-d1/ddl`, and the same order
	// `sqlite_master` reports back — which is what lets an introspected snapshot
	// compare equal to a schema-derived one.
	const suffix = [t.strict ? 'strict' : undefined, t.withoutRowid ? 'without rowid' : undefined]
		.filter((s) => s !== undefined);

	return `create table ${quote(t.name)} (\n${parts.map((p) => `\t${p}`).join(',\n')}\n)${
		suffix.length > 0 ? ` ${suffix.join(', ')}` : ''
	}`;
}

const referenceClause = (fk: ForeignKeySnapshot, quote: (name: string) => string): string =>
	` references ${quote(fk.tableTo)}(${quote(fk.columnsTo[0] ?? '')})`
	+ (fk.onDelete ? ` on delete ${fk.onDelete}` : '')
	+ (fk.onUpdate ? ` on update ${fk.onUpdate}` : '');

export function createIndexFromSnapshot(index: IndexSnapshot, tableName: string): string {
	const quote = (name: string): string => `"${name.replaceAll('"', '""')}"`;
	const renderColumn = (c: IndexColumnSnapshot): string => {
		const base = c.isExpression ? c.expression : quote(c.expression);
		const collate = c.collate ? ` collate ${c.collate}` : '';
		const order = c.desc ? ' desc' : '';
		return `${base}${collate}${order}`;
	};
	return `create ${index.isUnique ? 'unique ' : ''}index ${quote(index.name)} on ${quote(tableName)} (${
		index.columns.map(normalizeIndexColumn).map(renderColumn).join(', ')
	})${index.where ? ` where ${index.where}` : ''}`;
}

/**
 * The comparable form of a table.
 *
 * Two snapshots of the *same* schema do not have to be equal field for field,
 * because SQLite does not preserve everything a schema module states. It has
 * no way to report whether `unique` was written on the column or as a table
 * constraint, and it discards the declared name of a unique or foreign-key
 * constraint entirely — a `unique('post_tags_tag_unique')` comes back as
 * `sqlite_autoindex_post_tags_1`. Comparing raw snapshots therefore reported
 * drift on a database that exactly matched its schema, and `check` exited
 * non-zero forever while `push` rebuilt every table on every run.
 *
 * So comparison happens on this normalised shape instead: constraints are
 * lifted off columns to the table level, and identified by what they *do*
 * rather than by what they are called. Generation still reads the original
 * snapshot, which keeps the declared names in the emitted DDL.
 */
export interface CanonicalColumn {
	readonly type: string;
	/**
	 * The raw `declaredType` this column's `type` was derived from, when the
	 * snapshot carried one. `undefined` means this is a pre-`declaredType`
	 * snapshot (written before that field existed) — see `columnDifference`.
	 */
	readonly declaredType: string | undefined;
	readonly notNull: boolean;
	readonly default: string | null;
	readonly autoincrement: boolean;
	readonly generated: string | null;
	/**
	 * Folded to lowercase, with `binary` collapsed to `undefined` — same
	 * technique `canonicalIndex` (`diff.ts`) already applies to an index
	 * member's collation, for the same reason: D1 preserves a `COLLATE`
	 * clause's original case verbatim, so `collate NoCase` (live) and
	 * `NOCASE` (schema, hypothetically) would otherwise compare unequal.
	 * `undefined` here means "unstated or BINARY"; anything else is a real,
	 * reportable collation.
	 */
	readonly collate: string | undefined;
}

/**
 * The affinity rule `columnDifference` used before `declaredType` existed: a
 * plain substring search over the five canonical spellings, defaulting to
 * `'text'`. Kept only to reproduce what an old snapshot's `type` field means,
 * so upgrading past `declaredType` does not itself look like a type change.
 */
const legacyAffinity = (declared: string): string => {
	const lower = declared.toLowerCase();
	return ['integer', 'text', 'real', 'blob', 'numeric'].find((candidate) => lower.includes(candidate)) ?? 'text';
};

export interface CanonicalTable {
	readonly columns: Record<string, CanonicalColumn>;
	readonly primaryKey: string;
	readonly uniques: readonly string[];
	readonly foreignKeys: readonly string[];
	readonly checks: readonly string[];
	/** Part of the `CREATE TABLE`, so a change here means a rebuild. */
	readonly strict: boolean;
	readonly withoutRowid: boolean;
	/**
	 * A separate trigger object; changes without touching the table.
	 * Canonicalised by `appendOnlyKey` so a column list compares as a string.
	 */
	readonly appendOnly: string;
}

/**
 * Why two canonical columns differ, in the words the migration comment uses.
 * The tuple is compared field by field rather than as a blob so the reason
 * stays as specific as it was before normalisation.
 */
export const columnDifference = (
	a: CanonicalColumn,
	b: CanonicalColumn,
	/**
	 * Whether the snapshot `b` was derived from is schema-authored. Only then
	 * is `b.collate === undefined` structurally forced rather than a genuine
	 * statement of BINARY — see the comment below.
	 */
	bIsSchemaDerived: boolean,
): string | undefined => {
	if (a.type !== b.type && !typeMatchesAcrossUpgrade(a, b) && !typeMatchesAcrossUpgrade(b, a)) return 'changes type';
	if (a.notNull !== b.notNull) return 'changes nullability';
	if (a.default !== b.default) return 'changes its default';
	if (a.autoincrement !== b.autoincrement) return 'changes autoincrement';
	if (a.generated !== b.generated) return 'changes its generated expression';
	// A live column can carry a real, non-BINARY collation that the schema DSL
	// has no way to author (Drizzle has no `.collate()`), so `after.collate` is
	// `undefined` forever on a schema-derived snapshot even when the database
	// genuinely has one. That is "unexpressible", not "changed to binary" —
	// forcing a destructive recreate on the very first `generate` after a
	// `pull` would be a permanent, unfixable false positive. `pull` reports the
	// live value instead, via `unexpressibleTableOptionWarnings`.
	//
	// The exemption is keyed on `b` actually being schema-derived — not merely
	// on `b.collate` being `undefined` — because an introspected snapshot can
	// state `undefined` two genuine ways: never mentioned, or explicitly
	// `collate binary` (folded to `undefined` above). Keying on the value alone
	// hid introspection-to-introspection drift (a hand-rebuilt production
	// table gaining a real collation the pulled baseline never had) and made
	// an explicit `collate binary` on one side permanently unreachable against
	// a real collation on the other. Only a schema-derived `b` is structurally
	// incapable of stating one; everything else — schema-to-schema,
	// introspection-to-introspection, or a schema stating one where the live
	// db states another — still needs to be caught.
	if (!(bIsSchemaDerived && a.collate !== undefined && b.collate === undefined) && a.collate !== b.collate) {
		return 'changes its collation';
	}
	return undefined;
};

/**
 * Whether `old` (no `declaredType`, i.e. a pre-upgrade snapshot) and `fresh`
 * (carries a `declaredType`) actually describe the same type, once `old`'s
 * value is reinterpreted under the rule that produced it.
 *
 * A pre-`declaredType` snapshot's `type` was computed with the old substring
 * rule (`legacyAffinity`), not `affinityOf`'s real SQLite rules. Comparing the
 * two rules' outputs directly disagrees for plenty of customTypes even though
 * nothing about the schema changed — e.g. `customType(() => 'int')` was
 * recorded as `'text'` under the old rule but is `'integer'` under the new
 * one. So when one side has no `declaredType`, the two only really differ if
 * applying the OLD rule to the NEW side's `declaredType` still disagrees with
 * what the old snapshot recorded.
 *
 * Both sides carrying a `declaredType` skips this entirely — that comparison
 * stays the plain `a.type !== b.type` check, so a genuine type change between
 * two current-shaped snapshots is still caught.
 */
const typeMatchesAcrossUpgrade = (old: CanonicalColumn, fresh: CanonicalColumn): boolean => {
	if (old.declaredType !== undefined || fresh.declaredType === undefined) return false;
	return legacyAffinity(fresh.declaredType) === old.type;
};

/**
 * An expression default compares without its outer parentheses.
 *
 * `CREATE TABLE` *requires* them — `default (unixepoch())` is the only legal
 * spelling — but `pragma table_info` reports the expression with them stripped.
 * So the schema said `(unixepoch())`, the database said `unixepoch()`, and the
 * one idiom D1 users reach for most drifted against itself on every `check`
 * and `push`, taking a destructive rebuild with it.
 */
const canonicalDefault = (value: string | undefined): string | null => {
	if (value === undefined) return null;
	const text = value.trim();
	if (!text.startsWith('(') || !text.endsWith(')')) return text;

	// Only when the outer pair actually wraps the whole expression: `(a) + (b)`
	// starts and ends with a paren but is not parenthesised.
	let depth = 0;
	for (let i = 0; i < text.length; i++) {
		if (text[i] === '(') depth++;
		else if (text[i] === ')') {
			depth--;
			if (depth === 0 && i < text.length - 1) return text;
		}
	}
	return canonicalDefault(text.slice(1, -1));
};

/** Constraint names are not comparable, so everything is keyed by content. */
const canonicalFk = (fk: ForeignKeySnapshot): string =>
	JSON.stringify([
		[...fk.columns],
		fk.tableTo,
		[...fk.columnsTo],
		(fk.onDelete ?? 'no action').toLowerCase(),
		(fk.onUpdate ?? 'no action').toLowerCase(),
	]);

/**
 * SQLite's declared-type → affinity rules, verbatim from the documentation.
 *
 * A live database records whatever the `CREATE TABLE` said — `VARCHAR(255)`,
 * `BOOLEAN`, `DATETIME`, `INT` — while an orm-d1 schema only ever produces the
 * five canonical spellings. To SQLite those pairs are *identical*: affinity is
 * the whole of a column's type, and `VARCHAR(255)` is `TEXT`.
 *
 * Comparing the raw strings therefore reported a type change on every column of
 * every table that orm-d1 did not create — which `pull` then turned into a
 * destructive rebuild that rewrote the live types for no benefit. Compared by
 * affinity, a pulled schema is stable, and a genuine change (`INTEGER` to
 * `TEXT`) still differs because the affinities do.
 *
 * Order matters and is part of the rule: `INT` is checked before `CHAR`, so
 * `POINT` is INTEGER, as SQLite says it is.
 */
export const typeAffinity = (declared: string): 'integer' | 'text' | 'blob' | 'real' | 'numeric' => {
	const type = declared.toUpperCase();
	if (type.includes('INT')) return 'integer';
	if (type.includes('CHAR') || type.includes('CLOB') || type.includes('TEXT')) return 'text';
	// An empty declared type is BLOB; so is anything containing BLOB.
	if (type.includes('BLOB') || type.trim() === '') return 'blob';
	if (type.includes('REAL') || type.includes('FLOA') || type.includes('DOUB')) return 'real';
	return 'numeric';
};

export const canonicalTable = (table: TableSnapshot): CanonicalTable => {
	const columns: Record<string, CanonicalColumn> = {};
	const uniques: string[] = [];
	const foreignKeys: string[] = [];
	const primaryKeyColumns: string[] = [];

	// A single-column primary key is NOT NULL whether or not anyone wrote it:
	// SQLite reports it that way, and introspection records it. Spelling the
	// key as a table-level `primaryKey({ columns: [t.id] })` left the schema
	// side saying nullable, so the table rebuilt on every run.
	const lonePrimaryKey = new Set<string>();
	const composite = Object.values(table.compositePrimaryKeys);
	const compositeColumns = composite.flatMap((pk) => [...pk.columns]);
	if (compositeColumns.length === 1) lonePrimaryKey.add(compositeColumns[0]!);
	for (const column of Object.values(table.columns)) {
		if (column.primaryKey) lonePrimaryKey.add(column.name);
	}

	for (const [name, column] of Object.entries(table.columns)) {
		// `unique` and `references` are dropped here and re-added below, so a
		// column-level constraint and its table-level spelling compare equal.
		columns[name] = {
			// Affinity, not the declared spelling — see `typeAffinity`.
			type: typeAffinity(column.type),
			declaredType: column.declaredType,
			notNull: column.notNull || lonePrimaryKey.has(column.name),
			default: canonicalDefault(column.default),
			autoincrement: column.autoincrement,
			generated: column.generated
				? JSON.stringify({ ...column.generated, as: column.generated.as.replaceAll(/\s+/g, ' ').trim() })
				: null,
			collate: column.collate && column.collate.toLowerCase() !== 'binary'
				? column.collate.toLowerCase()
				: undefined,
		};
		if (column.primaryKey) primaryKeyColumns.push(column.name);
		if (column.unique) uniques.push(JSON.stringify([column.name]));
		if (column.references) foreignKeys.push(canonicalFk(column.references));
	}

	for (const pk of Object.values(table.compositePrimaryKeys)) primaryKeyColumns.push(...pk.columns);
	for (const u of Object.values(table.uniqueConstraints)) uniques.push(JSON.stringify([...u.columns]));
	for (const fk of Object.values(table.foreignKeys)) foreignKeys.push(canonicalFk(fk));

	return {
		columns,
		primaryKey: JSON.stringify(primaryKeyColumns),
		uniques: uniques.sort(),
		foreignKeys: foreignKeys.sort(),
		// SQLite keeps the check's text but not reliably its whitespace.
		checks: Object.values(table.checkConstraints)
			.map((c) => c.value.replaceAll(/\s+/g, ' ').trim())
			.sort(),
		strict: table.strict ?? false,
		withoutRowid: table.withoutRowid ?? false,
		appendOnly: appendOnlyKey(table.appendOnly),
	};
};

/** Sanity check: the snapshot must reproduce what the DDL generator emits. */
export const assertRoundTrip = (t: Table): void => {
	const snapshot = snapshotFromSchema([t]);
	const fromSnapshot = createTableFromSnapshot(snapshot.tables[getTableName(t)]!);
	const direct = createTable(t);
	if (fromSnapshot !== direct) {
		throw new Error(`Snapshot drift for "${getTableName(t)}":\n${direct}\n---\n${fromSnapshot}`);
	}
};
