/**
 * The snapshot: a normalised JSON description of a schema.
 *
 * Migrations are generated by diffing two of these, so the format is the
 * contract between `generate`, `pull` and `check`. It deliberately mirrors
 * drizzle-kit's shape — it is a reasonable design, and matching it is what
 * makes importing an existing migration history possible.
 */
import { createIndex, createTable, defaultExpression, foreignKeyName, literal, renderInline, uniqueConstraintName } from 'd1zzle/ddl';
import type { TableOptionsMap } from 'd1zzle/ddl';
import type { Column, Table } from 'd1zzle';
import { getTableColumns, getTableExtras, getTableName, isColumn } from 'd1zzle';

/**
 * `2` added `strict`, `withoutRowid` and `appendOnly` to `TableSnapshot`.
 *
 * A version-1 snapshot simply lacks the three fields, and they read as `false`,
 * which is exactly what a database written before they existed looks like. So
 * the bump is for diagnostics and `up`, not for correctness of the read path.
 */
export const SNAPSHOT_VERSION = '2';

export interface ColumnSnapshot {
	readonly name: string;
	readonly type: string;
	/**
	 * The exact string a `customType`'s `dataType(config)` declared, when this
	 * column has one — `d1zzle/ddl`'s `typeName()` emits this verbatim instead
	 * of `type` (which is only ever a reduced SQLite storage-class affinity).
	 * Absent on a snapshot written before this field existed, and absent for
	 * every non-`customType` column; both read as "no declared type", i.e. fall
	 * back to `type`. Comparison (`canonicalTable`) deliberately does not look
	 * at this — it stays affinity-based so a live D1 column's spelling never
	 * causes a spurious diff — only DDL *emission* needs the exact string.
	 */
	readonly declaredType?: string | undefined;
	readonly primaryKey: boolean;
	readonly notNull: boolean;
	readonly autoincrement: boolean;
	readonly unique: boolean;
	/** SQL text of the default, already literalised. `undefined` = no default. */
	readonly default?: string | undefined;
	readonly generated?: { readonly as: string; readonly mode: 'stored' | 'virtual' } | undefined;
	/** A column-level foreign key. Table-level ones live in `foreignKeys`. */
	readonly references?: ForeignKeySnapshot | undefined;
}

/**
 * One member of an index's column list.
 *
 * `isExpression: true` means `expression` is a SQL fragment (e.g.
 * `lower("email")` from `index(...).on(sql\`lower(${t.email})\`)`), not a bare
 * identifier — `createIndexFromSnapshot` must not quote it as one, or the
 * index binds to a constant string literal instead of the expression.
 *
 * A snapshot written before this shape existed has plain strings in
 * `columns` instead of `IndexColumnSnapshot` objects; every reader normalises
 * a bare string to `{ expression: <string>, isExpression: false }` — see
 * `normalizeIndexColumn`.
 */
export interface IndexColumnSnapshot {
	readonly expression: string;
	readonly isExpression: boolean;
}

/**
 * Reads either shape a `columns` entry can be on disk: the current
 * `IndexColumnSnapshot`, or a bare string from a pre-upgrade snapshot (always
 * an identifier, so `isExpression: false`).
 */
export const normalizeIndexColumn = (entry: string | IndexColumnSnapshot): IndexColumnSnapshot =>
	typeof entry === 'string' ? { expression: entry, isExpression: false } : entry;

export interface IndexSnapshot {
	readonly name: string;
	readonly columns: readonly (string | IndexColumnSnapshot)[];
	readonly isUnique: boolean;
	readonly where?: string | undefined;
}

export interface ForeignKeySnapshot {
	readonly name: string;
	readonly columns: readonly string[];
	readonly tableTo: string;
	readonly columnsTo: readonly string[];
	readonly onDelete?: string | undefined;
	readonly onUpdate?: string | undefined;
}

export interface TableSnapshot {
	readonly name: string;
	readonly columns: Record<string, ColumnSnapshot>;
	readonly indexes: Record<string, IndexSnapshot>;
	readonly foreignKeys: Record<string, ForeignKeySnapshot>;
	readonly compositePrimaryKeys: Record<string, { name: string; columns: readonly string[] }>;
	readonly uniqueConstraints: Record<string, { name: string; columns: readonly string[] }>;
	readonly checkConstraints: Record<string, { name: string; value: string }>;
	/**
	 * Physical-storage options and the append-only guard, from the sidecar
	 * `tableOptions()` module (see `d1zzle/ddl`). Optional so a version-1
	 * snapshot still parses; absent means `false`.
	 *
	 * `strict` and `withoutRowid` are properties of the `CREATE TABLE` itself, so
	 * changing either forces a full table rebuild. `appendOnly` is a separate
	 * trigger object, so it can be added or dropped in place — but it *is*
	 * dropped along with the table, so a rebuild has to re-emit it.
	 */
	readonly strict?: boolean;
	readonly withoutRowid?: boolean;
	readonly appendOnly?: boolean;
}

export interface Snapshot {
	readonly version: string;
	readonly dialect: 'sqlite';
	readonly id: string;
	readonly prevId: string;
	readonly tables: Record<string, TableSnapshot>;
	/**
	 * Where this snapshot came from. Only a schema-derived one knows the
	 * declared name of a unique, check or foreign-key constraint — SQLite does
	 * not store them, so an introspected snapshot carries whatever the engine
	 * made up (`sqlite_autoindex_users_1`). Anything that reasons about names
	 * has to check this first, or it reports a rename between every pair of
	 * snapshots that did not come from the same side. Absent on snapshots
	 * written before this field existed, which is treated as unknown.
	 */
	readonly origin?: 'schema' | 'introspection';
}

export const emptySnapshot = (id = '0'.repeat(8), prevId = ''): Snapshot => ({
	version: SNAPSHOT_VERSION,
	dialect: 'sqlite',
	id,
	prevId,
	tables: {},
	// It has no constraints to have names for, so it agrees with either side.
	origin: 'schema',
});

const defaultOf = (column: Column<any>): string | undefined => {
	const value = column.config.default;
	if (!value) return undefined;
	return value.kind === 'sql'
		? defaultExpression(renderInline(value.value as never))
		: literal(column.config.encode(value.value));
};

const columnSnapshot = (column: Column<any>): ColumnSnapshot => ({
	name: column.name,
	type: column.config.type,
	declaredType: column.config.declaredType,
	primaryKey: column.config.primaryKey,
	notNull: column.config.notNull,
	autoincrement: column.config.autoIncrement,
	unique: column.config.unique,
	default: defaultOf(column),
	generated: column.config.generated
		? { as: renderInline(column.config.generated.as), mode: column.config.generated.mode }
		: undefined,
	references: column.config.references
		? {
			name: `${column.tableName}_${column.name}_fk`,
			columns: [column.name],
			tableTo: column.config.references.ref().tableName,
			columnsTo: [column.config.references.ref().name],
			onDelete: column.config.references.onDelete,
			onUpdate: column.config.references.onUpdate,
		}
		: undefined,
});

/**
 * Build a snapshot from live schema objects.
 *
 * `options` is the sidecar `tableOptions()` map. It is separate from the schema
 * module because `STRICT` / `WITHOUT ROWID` / triggers have no spelling in
 * `drizzle-orm/sqlite-core`, and doc 08 keeps the schema DSL a strict subset of
 * it — see the `TableOptions` docs in `d1zzle/ddl`.
 */
export function snapshotFromSchema(
	schema: Record<string, unknown> | readonly Table[],
	id = '',
	options?: TableOptionsMap | undefined,
): Snapshot {
	const tables = Array.isArray(schema)
		? (schema as readonly Table[])
		: Object.values(schema as Record<string, unknown>).filter(isTableLike);

	const result: Record<string, TableSnapshot> = {};

	for (const t of tables) {
		const name = getTableName(t);
		const columns: Record<string, ColumnSnapshot> = {};
		for (const column of Object.values(getTableColumns(t)) as Column<any>[]) {
			columns[column.name] = columnSnapshot(column);
		}

		const indexes: Record<string, IndexSnapshot> = {};
		const foreignKeys: Record<string, ForeignKeySnapshot> = {};
		const compositePrimaryKeys: Record<string, { name: string; columns: readonly string[] }> = {};
		const uniqueConstraints: Record<string, { name: string; columns: readonly string[] }> = {};
		const checkConstraints: Record<string, { name: string; value: string }> = {};

		for (const extra of getTableExtras(t)) {
			switch (extra.kind) {
				case 'index': {
					// Reuse the DDL generator's naming, so a generated migration
					// and a `createSchema()` call cannot disagree.
					const statement = createIndex(extra.meta, name);
					const indexName = statement.match(/index (?:if not exists )?"((?:[^"]|"")+)"/)?.[1]
						?.replaceAll('""', '"') ?? '';
					indexes[indexName] = {
						name: indexName,
						columns: extra.meta.columns.map((c) =>
							isColumn(c)
								? { expression: c.name, isExpression: false }
								: { expression: renderInline(c as never), isExpression: true }
						),
						isUnique: extra.meta.unique,
						where: extra.meta.where ? renderInline(extra.meta.where) : undefined,
					};
					break;
				}
				case 'primaryKey': {
					const pkName = extra.meta.name ?? `${name}_pk`;
					compositePrimaryKeys[pkName] = {
						name: pkName,
						columns: extra.meta.columns.map((c) => c.name),
					};
					break;
				}
				case 'unique': {
					const uqName = uniqueConstraintName(extra.meta, name);
					uniqueConstraints[uqName] = { name: uqName, columns: extra.meta.columns.map((c) => c.name) };
					break;
				}
				case 'foreignKey': {
					// The derivation is imported, not restated: the snapshot keys
					// foreign keys by this name, so a spelling that differs from the
					// DDL's — or that omits the columns, as this one did — loses a
					// constraint to a collision between two unnamed keys.
					const fkName = foreignKeyName(extra.meta, name);
					foreignKeys[fkName] = {
						name: fkName,
						columns: extra.meta.columns.map((c) => c.name),
						tableTo: extra.meta.foreignColumns[0]?.tableName ?? '',
						columnsTo: extra.meta.foreignColumns.map((c) => c.name),
						onDelete: extra.meta.onDelete,
						onUpdate: extra.meta.onUpdate,
					};
					break;
				}
				case 'check': {
					checkConstraints[extra.meta.name] = {
						name: extra.meta.name,
						value: renderInline(extra.meta.value),
					};
					break;
				}
			}
		}

		const perTable = options?.byTable[name];
		result[name] = {
			name,
			columns,
			indexes,
			foreignKeys,
			compositePrimaryKeys,
			uniqueConstraints,
			checkConstraints,
			strict: perTable?.strict ?? false,
			withoutRowid: perTable?.withoutRowid ?? false,
			appendOnly: perTable?.appendOnly ?? false,
		};
	}

	return { version: SNAPSHOT_VERSION, dialect: 'sqlite', id, prevId: '', tables: result, origin: 'schema' };
}

const isTableLike = (value: unknown): value is Table =>
	typeof value === 'object' && value !== null
	&& Symbol.for('d1zzle:IsTable') in (value as Record<symbol, unknown>);

/** The `CREATE TABLE` a snapshot table implies, without needing live objects. */
export function createTableFromSnapshot(t: TableSnapshot): string {
	const quote = (name: string): string => `"${name.replaceAll('"', '""')}"`;
	const hasCompositePk = Object.keys(t.compositePrimaryKeys).length > 0;
	const parts: string[] = [];

	for (const column of Object.values(t.columns)) {
		let ddl = `${quote(column.name)} ${column.declaredType ?? column.type}`;
		if (!hasCompositePk && column.primaryKey) {
			ddl += ' primary key';
			if (column.autoincrement) ddl += ' autoincrement';
		}
		if (column.notNull) ddl += ' not null';
		if (column.unique) ddl += ' unique';
		if (column.generated) ddl += ` generated always as (${column.generated.as}) ${column.generated.mode}`;
		if (column.default !== undefined) ddl += ` default ${column.default}`;
		if (column.references) ddl += referenceClause(column.references, quote);
		parts.push(ddl);
	}

	for (const pk of Object.values(t.compositePrimaryKeys)) {
		parts.push(`constraint ${quote(pk.name)} primary key (${pk.columns.map(quote).join(', ')})`);
	}
	for (const uq of Object.values(t.uniqueConstraints)) {
		parts.push(`constraint ${quote(uq.name)} unique (${uq.columns.map(quote).join(', ')})`);
	}
	for (const fk of Object.values(t.foreignKeys)) {
		parts.push(
			`constraint ${quote(fk.name)} foreign key (${fk.columns.map(quote).join(', ')})`
				+ ` references ${quote(fk.tableTo)}(${fk.columnsTo.map(quote).join(', ')})`
				+ (fk.onDelete ? ` on delete ${fk.onDelete}` : '')
				+ (fk.onUpdate ? ` on update ${fk.onUpdate}` : ''),
		);
	}
	for (const check of Object.values(t.checkConstraints)) {
		parts.push(`constraint ${quote(check.name)} check (${check.value})`);
	}

	// Same order as `createTable` in `d1zzle/ddl`, and the same order
	// `sqlite_master` reports back — which is what lets an introspected snapshot
	// compare equal to a schema-derived one.
	const suffix = [t.strict ? 'strict' : undefined, t.withoutRowid ? 'without rowid' : undefined]
		.filter((s) => s !== undefined);

	return `create table ${quote(t.name)} (\n${parts.map((p) => `\t${p}`).join(',\n')}\n)${
		suffix.length > 0 ? ` ${suffix.join(', ')}` : ''
	}`;
}

const referenceClause = (fk: ForeignKeySnapshot, quote: (name: string) => string): string =>
	` references ${quote(fk.tableTo)}(${quote(fk.columnsTo[0] ?? '')})`
	+ (fk.onDelete ? ` on delete ${fk.onDelete}` : '')
	+ (fk.onUpdate ? ` on update ${fk.onUpdate}` : '');

export function createIndexFromSnapshot(index: IndexSnapshot, tableName: string): string {
	const quote = (name: string): string => `"${name.replaceAll('"', '""')}"`;
	return `create ${index.isUnique ? 'unique ' : ''}index ${quote(index.name)} on ${quote(tableName)} (${
		index.columns.map(normalizeIndexColumn).map((c) => (c.isExpression ? c.expression : quote(c.expression))).join(', ')
	})${index.where ? ` where ${index.where}` : ''}`;
}

/**
 * The comparable form of a table.
 *
 * Two snapshots of the *same* schema do not have to be equal field for field,
 * because SQLite does not preserve everything a schema module states. It has
 * no way to report whether `unique` was written on the column or as a table
 * constraint, and it discards the declared name of a unique or foreign-key
 * constraint entirely — a `unique('post_tags_tag_unique')` comes back as
 * `sqlite_autoindex_post_tags_1`. Comparing raw snapshots therefore reported
 * drift on a database that exactly matched its schema, and `check` exited
 * non-zero forever while `push` rebuilt every table on every run.
 *
 * So comparison happens on this normalised shape instead: constraints are
 * lifted off columns to the table level, and identified by what they *do*
 * rather than by what they are called. Generation still reads the original
 * snapshot, which keeps the declared names in the emitted DDL.
 */
export interface CanonicalColumn {
	readonly type: string;
	/**
	 * The raw `declaredType` this column's `type` was derived from, when the
	 * snapshot carried one. `undefined` means this is a pre-`declaredType`
	 * snapshot (written before that field existed) — see `columnDifference`.
	 */
	readonly declaredType: string | undefined;
	readonly notNull: boolean;
	readonly default: string | null;
	readonly autoincrement: boolean;
	readonly generated: string | null;
}

/**
 * The affinity rule `columnDifference` used before `declaredType` existed: a
 * plain substring search over the five canonical spellings, defaulting to
 * `'text'`. Kept only to reproduce what an old snapshot's `type` field means,
 * so upgrading past `declaredType` does not itself look like a type change.
 */
const legacyAffinity = (declared: string): string => {
	const lower = declared.toLowerCase();
	return ['integer', 'text', 'real', 'blob', 'numeric'].find((candidate) => lower.includes(candidate)) ?? 'text';
};

export interface CanonicalTable {
	readonly columns: Record<string, CanonicalColumn>;
	readonly primaryKey: string;
	readonly uniques: readonly string[];
	readonly foreignKeys: readonly string[];
	readonly checks: readonly string[];
	/** Part of the `CREATE TABLE`, so a change here means a rebuild. */
	readonly strict: boolean;
	readonly withoutRowid: boolean;
	/** A separate trigger object; changes without touching the table. */
	readonly appendOnly: boolean;
}

/**
 * Why two canonical columns differ, in the words the migration comment uses.
 * The tuple is compared field by field rather than as a blob so the reason
 * stays as specific as it was before normalisation.
 */
export const columnDifference = (a: CanonicalColumn, b: CanonicalColumn): string | undefined => {
	if (a.type !== b.type && !typeMatchesAcrossUpgrade(a, b) && !typeMatchesAcrossUpgrade(b, a)) return 'changes type';
	if (a.notNull !== b.notNull) return 'changes nullability';
	if (a.default !== b.default) return 'changes its default';
	if (a.autoincrement !== b.autoincrement) return 'changes autoincrement';
	if (a.generated !== b.generated) return 'changes its generated expression';
	return undefined;
};

/**
 * Whether `old` (no `declaredType`, i.e. a pre-upgrade snapshot) and `fresh`
 * (carries a `declaredType`) actually describe the same type, once `old`'s
 * value is reinterpreted under the rule that produced it.
 *
 * A pre-`declaredType` snapshot's `type` was computed with the old substring
 * rule (`legacyAffinity`), not `affinityOf`'s real SQLite rules. Comparing the
 * two rules' outputs directly disagrees for plenty of customTypes even though
 * nothing about the schema changed — e.g. `customType(() => 'int')` was
 * recorded as `'text'` under the old rule but is `'integer'` under the new
 * one. So when one side has no `declaredType`, the two only really differ if
 * applying the OLD rule to the NEW side's `declaredType` still disagrees with
 * what the old snapshot recorded.
 *
 * Both sides carrying a `declaredType` skips this entirely — that comparison
 * stays the plain `a.type !== b.type` check, so a genuine type change between
 * two current-shaped snapshots is still caught.
 */
const typeMatchesAcrossUpgrade = (old: CanonicalColumn, fresh: CanonicalColumn): boolean => {
	if (old.declaredType !== undefined || fresh.declaredType === undefined) return false;
	return legacyAffinity(fresh.declaredType) === old.type;
};

/**
 * An expression default compares without its outer parentheses.
 *
 * `CREATE TABLE` *requires* them — `default (unixepoch())` is the only legal
 * spelling — but `pragma table_info` reports the expression with them stripped.
 * So the schema said `(unixepoch())`, the database said `unixepoch()`, and the
 * one idiom D1 users reach for most drifted against itself on every `check`
 * and `push`, taking a destructive rebuild with it.
 */
const canonicalDefault = (value: string | undefined): string | null => {
	if (value === undefined) return null;
	const text = value.trim();
	if (!text.startsWith('(') || !text.endsWith(')')) return text;

	// Only when the outer pair actually wraps the whole expression: `(a) + (b)`
	// starts and ends with a paren but is not parenthesised.
	let depth = 0;
	for (let i = 0; i < text.length; i++) {
		if (text[i] === '(') depth++;
		else if (text[i] === ')') {
			depth--;
			if (depth === 0 && i < text.length - 1) return text;
		}
	}
	return canonicalDefault(text.slice(1, -1));
};

/** Constraint names are not comparable, so everything is keyed by content. */
const canonicalFk = (fk: ForeignKeySnapshot): string =>
	JSON.stringify([
		[...fk.columns],
		fk.tableTo,
		[...fk.columnsTo],
		(fk.onDelete ?? 'no action').toLowerCase(),
		(fk.onUpdate ?? 'no action').toLowerCase(),
	]);

/**
 * SQLite's declared-type → affinity rules, verbatim from the documentation.
 *
 * A live database records whatever the `CREATE TABLE` said — `VARCHAR(255)`,
 * `BOOLEAN`, `DATETIME`, `INT` — while a d1zzle schema only ever produces the
 * five canonical spellings. To SQLite those pairs are *identical*: affinity is
 * the whole of a column's type, and `VARCHAR(255)` is `TEXT`.
 *
 * Comparing the raw strings therefore reported a type change on every column of
 * every table that d1zzle did not create — which `pull` then turned into a
 * destructive rebuild that rewrote the live types for no benefit. Compared by
 * affinity, a pulled schema is stable, and a genuine change (`INTEGER` to
 * `TEXT`) still differs because the affinities do.
 *
 * Order matters and is part of the rule: `INT` is checked before `CHAR`, so
 * `POINT` is INTEGER, as SQLite says it is.
 */
export const typeAffinity = (declared: string): 'integer' | 'text' | 'blob' | 'real' | 'numeric' => {
	const type = declared.toUpperCase();
	if (type.includes('INT')) return 'integer';
	if (type.includes('CHAR') || type.includes('CLOB') || type.includes('TEXT')) return 'text';
	// An empty declared type is BLOB; so is anything containing BLOB.
	if (type.includes('BLOB') || type.trim() === '') return 'blob';
	if (type.includes('REAL') || type.includes('FLOA') || type.includes('DOUB')) return 'real';
	return 'numeric';
};

export const canonicalTable = (table: TableSnapshot): CanonicalTable => {
	const columns: Record<string, CanonicalColumn> = {};
	const uniques: string[] = [];
	const foreignKeys: string[] = [];
	const primaryKeyColumns: string[] = [];

	// A single-column primary key is NOT NULL whether or not anyone wrote it:
	// SQLite reports it that way, and introspection records it. Spelling the
	// key as a table-level `primaryKey({ columns: [t.id] })` left the schema
	// side saying nullable, so the table rebuilt on every run.
	const lonePrimaryKey = new Set<string>();
	const composite = Object.values(table.compositePrimaryKeys);
	const compositeColumns = composite.flatMap((pk) => [...pk.columns]);
	if (compositeColumns.length === 1) lonePrimaryKey.add(compositeColumns[0]!);
	for (const column of Object.values(table.columns)) {
		if (column.primaryKey) lonePrimaryKey.add(column.name);
	}

	for (const [name, column] of Object.entries(table.columns)) {
		// `unique` and `references` are dropped here and re-added below, so a
		// column-level constraint and its table-level spelling compare equal.
		columns[name] = {
			// Affinity, not the declared spelling — see `typeAffinity`.
			type: typeAffinity(column.type),
			declaredType: column.declaredType,
			notNull: column.notNull || lonePrimaryKey.has(column.name),
			default: canonicalDefault(column.default),
			autoincrement: column.autoincrement,
			generated: column.generated
				? JSON.stringify({ ...column.generated, as: column.generated.as.replaceAll(/\s+/g, ' ').trim() })
				: null,
		};
		if (column.primaryKey) primaryKeyColumns.push(column.name);
		if (column.unique) uniques.push(JSON.stringify([column.name]));
		if (column.references) foreignKeys.push(canonicalFk(column.references));
	}

	for (const pk of Object.values(table.compositePrimaryKeys)) primaryKeyColumns.push(...pk.columns);
	for (const u of Object.values(table.uniqueConstraints)) uniques.push(JSON.stringify([...u.columns]));
	for (const fk of Object.values(table.foreignKeys)) foreignKeys.push(canonicalFk(fk));

	return {
		columns,
		primaryKey: JSON.stringify(primaryKeyColumns),
		uniques: uniques.sort(),
		foreignKeys: foreignKeys.sort(),
		// SQLite keeps the check's text but not reliably its whitespace.
		checks: Object.values(table.checkConstraints)
			.map((c) => c.value.replaceAll(/\s+/g, ' ').trim())
			.sort(),
		strict: table.strict ?? false,
		withoutRowid: table.withoutRowid ?? false,
		appendOnly: table.appendOnly ?? false,
	};
};

/** Sanity check: the snapshot must reproduce what the DDL generator emits. */
export const assertRoundTrip = (t: Table): void => {
	const snapshot = snapshotFromSchema([t]);
	const fromSnapshot = createTableFromSnapshot(snapshot.tables[getTableName(t)]!);
	const direct = createTable(t);
	if (fromSnapshot !== direct) {
		throw new Error(`Snapshot drift for "${getTableName(t)}":\n${direct}\n---\n${fromSnapshot}`);
	}
};
