/**
 * The snapshot: a normalised JSON description of a schema.
 *
 * Migrations are generated by diffing two of these, so the format is the
 * contract between `generate`, `pull` and `check`. It deliberately mirrors
 * drizzle-kit's shape — it is a reasonable design, and matching it is what
 * makes importing an existing migration history possible.
 */
import { createTable, defaultExpression, foreignKeyName, indexName, literal, renderInline, uniqueConstraintName, withDDLContext } from 'orm-d1/ddl';
import type { TableOptionsMap } from 'orm-d1/ddl';
import { appendOnlyKey, assertAppendOnlyColumns } from 'orm-d1/ddl';
import type { Column, Table } from 'orm-d1';
import { getTableColumns, getTableExtras, getTableName, isColumn } from 'orm-d1';

/**
 * What a table's `appendOnly` option becomes in the snapshot.
 *
 * The column list is validated here as well as in `createSchema`, because the
 * snapshot is written by `generate` before any DDL is rendered: without this a
 * typo'd column name would be recorded as the guard, and SQLite accepts such a
 * trigger silently (see `assertAppendOnlyColumns`).
 */
const appendOnlySnapshotValue = (
	t: Table,
	value: boolean | readonly string[] | undefined,
): boolean | readonly string[] => {
	if (!value) return false;
	if (value === true) return true;
	return assertAppendOnlyColumns(t, value);
};

/**
 * `2` added `strict`, `withoutRowid` and `appendOnly` to `TableSnapshot`.
 * `3` widened `appendOnly` from `boolean` to `boolean | string[]`.
 *
 * A version-1 snapshot simply lacks the three fields, and they read as `false`,
 * which is exactly what a database written before they existed looks like. A
 * version-2 snapshot only ever holds `true` or `false`, which version 3 still
 * reads unchanged. So both bumps are for diagnostics and `up`, not for
 * correctness of the read path.
 */
export const SNAPSHOT_VERSION = '3';

export interface ColumnSnapshot {
	readonly name: string;
	readonly type: string;
	/**
	 * The exact string a `customType`'s `dataType(config)` declared, when this
	 * column has one — `orm-d1/ddl`'s `typeName()` emits this verbatim instead
	 * of `type` (which is only ever a reduced SQLite storage-class affinity).
	 * Absent on a snapshot written before this field existed, and absent for
	 * every non-`customType` column; both read as "no declared type", i.e. fall
	 * back to `type`. Comparison (`canonicalTable`) deliberately does not look
	 * at this — it stays affinity-based so a live D1 column's spelling never
	 * causes a spurious diff — only DDL *emission* needs the exact string.
	 */
	readonly declaredType?: string | undefined;
	readonly primaryKey: boolean;
	readonly notNull: boolean;
	readonly autoincrement: boolean;
	readonly unique: boolean;
	/** SQL text of the default, already literalised. `undefined` = no default. */
	readonly default?: string | undefined;
	readonly generated?: { readonly as: string; readonly mode: 'stored' | 'virtual' } | undefined;
	/** A column-level foreign key. Table-level ones live in `foreignKeys`. */
	readonly references?: ForeignKeySnapshot | undefined;
	/**
	 * The column's own `COLLATE` clause, in whatever case the DDL text used.
	 * `undefined` means "not stated" — which is also what a schema-derived
	 * snapshot always has, since Drizzle (and so orm-d1) has no `.collate()`
	 * spelling. `undefined` and an explicit `binary` are equivalent (BINARY is
	 * SQLite's default), but `undefined` against any *other* live collation
	 * (e.g. `nocase`) is a real, reportable difference — see `canonicalTable`.
	 */
	readonly collate?: string | undefined;
	/**
	 * True when `collate` (or its absence) is an explicit statement of intent —
	 * from the `tableOptions()` sidecar's `collate` map (`orm-d1/ddl`) — rather
	 * than structurally forced by the schema DSL having no `.collate()`
	 * spelling. Only a schema-derived snapshot ever sets this; an introspected
	 * one always reads the live `COLLATE` clause directly and has no need for
	 * it. Lets `generate`'s collation carry-forward (`[F-115]`) and
	 * `columnDifference`'s "unexpressible" exemption both tell "the schema
	 * cannot say this" apart from "the operator said so, including 'gone'".
	 */
	readonly collateStated?: boolean | undefined;
}

/**
 * One member of an index's column list.
 *
 * `isExpression: true` means `expression` is a SQL fragment (e.g.
 * `lower("email")` from `index(...).on(sql\`lower(${t.email})\`)`), not a bare
 * identifier — `createIndexFromSnapshot` must not quote it as one, or the
 * index binds to a constant string literal instead of the expression.
 *
 * A snapshot written before this shape existed has plain strings in
 * `columns` instead of `IndexColumnSnapshot` objects; every reader normalises
 * a bare string to `{ expression: <string>, isExpression: false }` — see
 * `normalizeIndexColumn`.
 */
export interface IndexColumnSnapshot {
	readonly expression: string;
	readonly isExpression: boolean;
	/** `DESC` in the index's column list. Absent/`false` means ascending, SQLite's default. */
	readonly desc?: boolean;
	/**
	 * An explicit `COLLATE <name>` on this index member. Absent means the
	 * column's own declared collation (or `BINARY`) applies — SQLite reports
	 * every member's collation, including the implicit default, so this is
	 * only set when it differs from `BINARY`, the default for an unqualified
	 * column, to keep an ordinary index from growing a spurious `collate`.
	 */
	readonly collate?: string;
}

/**
 * Reads either shape a `columns` entry can be on disk: the current
 * `IndexColumnSnapshot`, or a bare string from a pre-upgrade snapshot (always
 * an identifier, so `isExpression: false`).
 */
export const normalizeIndexColumn = (entry: string | IndexColumnSnapshot): IndexColumnSnapshot =>
	typeof entry === 'string' ? { expression: entry, isExpression: false } : entry;

/**
 * Drizzle's `IndexColumn` (`SQLiteColumn | SQL`, `drizzle-orm/sqlite-core`)
 * has no `.desc()`/`.collate()` on the column builder — there is no
 * first-class spelling for a DESC or COLLATE index member, only the raw-SQL
 * escape hatch already used for an expression index. A schema author states
 * one as `sql\`"col" collate NOCASE desc\``, which arrives here as an opaque
 * expression string identical in shape to `sql\`lower("col")\`` — but it
 * isn't one: it is a plain column, decorated, and `pragma index_xinfo`
 * reports it as exactly that (`cid` pointing at the real column, `desc`/`coll`
 * set), not as an expression member (`cid: -2`). Left undecomposed, a
 * schema-declared DESC/COLLATE index would permanently diff against the
 * database it exactly describes. So a raw-SQL member that is nothing but a
 * quoted identifier plus an optional `collate <name>` and/or `desc`/`asc` is
 * parsed back into the same structured shape introspection produces —
 * mirroring `parseIndexColumns`, which does the same job in the other
 * direction for expression members.
 */
const decorateIndexColumn = (raw: string): IndexColumnSnapshot => {
	const match = raw.trim().match(
		/^"((?:[^"]|"")+)"(?:\s+collate\s+(\w+))?(?:\s+(asc|desc))?$/i,
	);
	if (!match) return { expression: raw, isExpression: true };
	const [, name, collate, order] = match;
	return {
		expression: (name ?? '').replaceAll('""', '"'),
		isExpression: false,
		...(order?.toLowerCase() === 'desc' ? { desc: true } : {}),
		// Folded the same way `canonicalIndex` (diff.ts) folds the
		// introspected side, so `collate NOCASE` here and `collate NoCase`
		// read back from a live DB's DDL compare equal instead of spuriously
		// diffing on case alone.
		...(collate && collate.toLowerCase() !== 'binary' ? { collate: collate.toLowerCase() } : {}),
	};
};

/**
 * One member of a table-level `UNIQUE (…)` constraint.
 *
 * SQLite allows a member to carry its own `COLLATE`, e.g.
 * `constraint "u1" unique ("email" collate nocase)` — distinct from a
 * `.unique()` column's *own* `collate`, which is already carried on
 * `ColumnSnapshot.collate`. Column-level `unique` (whether combined with a
 * column-level `collate` or not) never produces a member here at all — it is
 * reported as `{ expression: [column.name] }` via `columns.push([...])` on
 * the column loop, never through this table-level shape. A snapshot written
 * before this shape existed has plain strings instead, normalised by
 * {@link normalizeUniqueColumn} the same way `normalizeIndexColumn` does for
 * an index member (`[F-111]`).
 */
export interface UniqueColumnSnapshot {
	readonly name: string;
	readonly collate?: string;
}

export const normalizeUniqueColumn = (entry: string | UniqueColumnSnapshot): UniqueColumnSnapshot =>
	typeof entry === 'string' ? { name: entry } : entry;

export interface IndexSnapshot {
	readonly name: string;
	readonly columns: readonly (string | IndexColumnSnapshot)[];
	readonly isUnique: boolean;
	readonly where?: string | undefined;
}

export interface ForeignKeySnapshot {
	readonly name: string;
	readonly columns: readonly string[];
	readonly tableTo: string;
	readonly columnsTo: readonly string[];
	readonly onDelete?: string | undefined;
	readonly onUpdate?: string | undefined;
	/** See `TableSnapshot.uniqueConstraints`'s note on `declarationOrder`. */
	readonly declarationOrder?: number;
}

export interface TableSnapshot {
	readonly name: string;
	readonly columns: Record<string, ColumnSnapshot>;
	readonly indexes: Record<string, IndexSnapshot>;
	readonly foreignKeys: Record<string, ForeignKeySnapshot>;
	/**
	 * `columns` holds either a bare member name or an `{ name, collate }` pair,
	 * same shape and same reason as `uniqueConstraints.columns` just below
	 * (`[F-115]`: a composite primary key member can carry its own `COLLATE`
	 * exactly like a unique constraint member can — `docs/04` gives the schema
	 * DSL no spelling for it either, so a schema-derived snapshot only ever
	 * has bare names here).
	 */
	readonly compositePrimaryKeys: Record<string, { name: string; columns: readonly (string | UniqueColumnSnapshot)[] }>;
	/**
	 * `columns` holds either a bare member name or an `{ name, collate }` pair —
	 * see {@link UniqueColumnSnapshot} and {@link normalizeUniqueColumn}.
	 *
	 * `declarationOrder`, on this and on `foreignKeys`/`checkConstraints`, is
	 * schema-origin only: `snapshotFromSchema` stamps it with each extra's
	 * position among *all* table-level extras (interleaved across kinds, the
	 * order `createTable` walks them in). `createTableFromSnapshot` uses it to
	 * emit unique/foreign-key/check constraints interleaved the same way,
	 * instead of grouped by kind — grouping made `assertRoundTrip`'s invariant
	 * hold only for a schema that happened to declare its extras in that
	 * grouped order (`[F-103]`). An introspected snapshot has no such concept
	 * and leaves it `undefined`; `createTableFromSnapshot` falls back to
	 * declaration order within each `Record`, which is what it already did.
	 */
	readonly uniqueConstraints: Record<
		string,
		{ name: string; columns: readonly (string | UniqueColumnSnapshot)[]; declarationOrder?: number }
	>;
	readonly checkConstraints: Record<string, { name: string; value: string; declarationOrder?: number }>;
	/**
	 * Physical-storage options and the append-only guard, from the sidecar
	 * `tableOptions()` module (see `orm-d1/ddl`). Optional so a version-1
	 * snapshot still parses; absent means `false`.
	 *
	 * `strict` and `withoutRowid` are properties of the `CREATE TABLE` itself, so
	 * changing either forces a full table rebuild. `appendOnly` is a separate
	 * trigger object, so it can be added or dropped in place — but it *is*
	 * dropped along with the table, so a rebuild has to re-emit it.
	 *
	 * `appendOnly` is `true` for a whole-table guard, or the list of columns a
	 * column-scoped guard covers. Narrowing or widening that list is also a
	 * trigger-only change.
	 */
	readonly strict?: boolean;
	readonly withoutRowid?: boolean;
	readonly appendOnly?: boolean | readonly string[];
}

export interface Snapshot {
	readonly version: string;
	readonly dialect: 'sqlite';
	readonly id: string;
	readonly prevId: string;
	readonly tables: Record<string, TableSnapshot>;
	/**
	 * Where this snapshot came from. Only a schema-derived one knows the
	 * declared name of a unique, check or foreign-key constraint — SQLite does
	 * not store them, so an introspected snapshot carries whatever the engine
	 * made up (`sqlite_autoindex_users_1`). Anything that reasons about names
	 * has to check this first, or it reports a rename between every pair of
	 * snapshots that did not come from the same side. Absent on snapshots
	 * written before this field existed, which is treated as unknown.
	 */
	readonly origin?: 'schema' | 'introspection';
}

export const emptySnapshot = (id = '0'.repeat(8), prevId = ''): Snapshot => ({
	version: SNAPSHOT_VERSION,
	dialect: 'sqlite',
	id,
	prevId,
	tables: {},
	// It has no constraints to have names for, so it agrees with either side.
	origin: 'schema',
});

const defaultOf = (column: Column<any>): string | undefined => {
	const value = column.config.default;
	if (!value) return undefined;
	return value.kind === 'sql'
		? defaultExpression(renderInline(value.value as never))
		: literal(column.config.encode(value.value));
};

const columnSnapshot = (column: Column<any>): ColumnSnapshot => ({
	name: column.name,
	type: column.config.type,
	declaredType: column.config.declaredType,
	primaryKey: column.config.primaryKey,
	notNull: column.config.notNull,
	autoincrement: column.config.autoIncrement,
	unique: column.config.unique,
	default: defaultOf(column),
	generated: column.config.generated
		? { as: renderInline(column.config.generated.as), mode: column.config.generated.mode }
		: undefined,
	references: column.config.references
		? {
			name: `${column.tableName}_${column.name}_fk`,
			columns: [column.name],
			tableTo: column.config.references.ref().tableName,
			columnsTo: [column.config.references.ref().name],
			onDelete: column.config.references.onDelete,
			onUpdate: column.config.references.onUpdate,
		}
		: undefined,
});

/**
 * Build a snapshot from live schema objects.
 *
 * `options` is the sidecar `tableOptions()` map. It is separate from the schema
 * module because `STRICT` / `WITHOUT ROWID` / triggers have no spelling in
 * `drizzle-orm/sqlite-core`, and docs/04 keeps the schema DSL a strict subset of
 * it — see the `TableOptions` docs in `orm-d1/ddl`.
 */
export function snapshotFromSchema(
	schema: Record<string, unknown> | readonly Table[],
	id = '',
	options?: TableOptionsMap | undefined,
): Snapshot {
	const tables = Array.isArray(schema)
		? (schema as readonly Table[])
		: Object.values(schema as Record<string, unknown>).filter(isTableLike);

	const result: Record<string, TableSnapshot> = {};

	for (const t of tables) {
		const name = getTableName(t);
		// `Object.create(null)`, not `{}` — same hazard as `indexes`/`foreignKeys`/
		// etc. below, just for the column name itself instead of a constraint
		// name. A column literally named `__proto__` (legal SQL, legal in the
		// schema DSL: `sqliteTable('t', { p: text('__proto__') })`) assigned
		// through a plain object sets the object's *prototype* instead of adding
		// an entry — the column silently vanishes from the snapshot, with no
		// error, and `createTableFromSnapshot`/`diffSnapshots` both read the same
		// dropped snapshot back, so a rebuild for any unrelated reason silently
		// drops the column and its data.
		const columns: Record<string, ColumnSnapshot> = Object.create(null);
		for (const column of Object.values(getTableColumns(t)) as Column<any>[]) {
			columns[column.name] = columnSnapshot(column);
		}

		// `[F-115]`: apply the sidecar's stated collation intent, if any, before
		// this snapshot is handed anywhere else. A `null` states "no collation" —
		// as distinct from the DSL's structural inability to say anything at
		// all — so `collateStated` is set either way.
		const collateOptions = options?.byTable[name]?.collate;
		if (collateOptions) {
			for (const [columnName, value] of Object.entries(collateOptions)) {
				// `Object.hasOwn`, not a bracket-and-truthiness read: `collateOptions`
				// is a plain object the sidecar file supplies, so a stated column
				// name of `toString` (or `constructor`, `valueOf`, …) that the table
				// does not actually have resolves `columns[columnName]` to an
				// inherited `Object.prototype` member instead of `undefined` — the
				// `if (!existing) continue` guard below then never fires, and
				// spreading that function into a "column snapshot" injects a bogus
				// entry with none of `ColumnSnapshot`'s required fields.
				if (!Object.hasOwn(columns, columnName)) continue;
				const existing = columns[columnName];
				if (!existing) continue;
				columns[columnName] = {
					...existing,
					collate: value === null || value.toLowerCase() === 'binary' ? undefined : value.toLowerCase(),
					collateStated: true,
				};
			}
		}

		// `Object.create(null)`, not `{}`: a constraint's derived or explicit name
		// is attacker- or DB-controlled text (`pull` on a foreign database emits
		// whatever names it finds), and a plain object literal treats a name like
		// `constructor` or `__proto__` specially — the former reads back an
		// inherited function instead of `undefined`, so the collision check below
		// would misfire on a name that was never actually used, and the latter
		// silently sets the object's prototype instead of adding an entry,
		// dropping the constraint with no error at all. A null-prototype object
		// has no inherited keys and no `__proto__` accessor, so every name is
		// just data.
		const indexes: Record<string, IndexSnapshot> = Object.create(null);
		const foreignKeys: Record<string, ForeignKeySnapshot> = Object.create(null);
		const compositePrimaryKeys: Record<string, { name: string; columns: readonly string[] }> = Object.create(null);
		const uniqueConstraints: TableSnapshot['uniqueConstraints'] = Object.create(null);
		const checkConstraints: TableSnapshot['checkConstraints'] = Object.create(null);

		// `createTable` (`orm-d1/ddl`) walks `extras` in declaration order and
		// emits a unique/foreign-key/check constraint inline as it reaches it;
		// this snapshot instead buckets them by kind. Stamping each one with its
		// position among only these three kinds — the same three `createTable`
		// interleaves — lets `createTableFromSnapshot` reproduce that interleaving
		// (`[F-103]`) instead of grouping all uniques, then all foreign keys, then
		// all checks, which only reproduced `createTable`'s output for a schema
		// that happened to declare its extras in that grouped order.
		let tailOrder = 0;

		for (const extra of getTableExtras(t)) {
			switch (extra.kind) {
				case 'index': {
					// Reuse the DDL generator's own name derivation directly — it is
					// already exported alongside `foreignKeyName`/`uniqueConstraintName`
					// (same import statement above) and used by both of those siblings.
					// The previous approach rendered the whole `CREATE INDEX` statement
					// just to regex the name back out of it, including `renderInline`
					// of the partial-index predicate — fragile and unnecessary next to
					// two direct derivations right beside it (`[F-028]`).
					const derivedName = indexName(extra.meta, name);
					if (Object.hasOwn(indexes, derivedName)) {
						const columns = extra.meta.columns.map((c) =>
							isColumn(c) ? c.name : renderInline(c as never)
						).join(', ');
						throw new Error(
							`"${name}" declares two indexes that both derive the name "${derivedName}" `
								+ `(the second is on "${columns}"). `
								+ 'Give at least one an explicit name — an unnamed expression index is named "expr" '
								+ 'whatever the expression is, so the second would silently replace the first.',
						);
					}
					indexes[derivedName] = {
						name: derivedName,
						// Wrapped through `withDDLContext`, the same as the `where` render
						// just below and the `check` branch further down: a refusal this can
						// throw (the empty-array DDL refusal, `src/ddl.ts`'s
						// `onEmptyArrayPredicate`/`onForeignFragment`) comes back anonymous
						// otherwise — no table or constraint name — because this runs before
						// `checkDDL` would normally attach that context. A refactor once
						// called `createIndex(extra.meta, name)` here purely to get its
						// `withDDLContext(name, indexName(...))` wrapper "for free"; removing
						// that call for `[F-028]` (this index's own name is now derived
						// directly via `indexName` above) also removed the wrapper. The
						// `where` render below was re-wrapped, but this column-expression
						// render was left bare — a sibling regression: an expression-column
						// index with an empty-array predicate (`index(...).on(inArray(c, []))`)
						// still threw an anonymous refusal.
						columns: withDDLContext(
							name,
							derivedName,
							() =>
								extra.meta.columns.map((c) =>
									isColumn(c)
										? { expression: c.name, isExpression: false }
										: decorateIndexColumn(renderInline(c as never))
								),
						),
						isUnique: extra.meta.unique,
						where: extra.meta.where
							? withDDLContext(name, derivedName, () => renderInline(extra.meta.where!, true))
							: undefined,
					};
					break;
				}
				case 'primaryKey': {
					const pkName = extra.meta.name ?? `${name}_pk`;
					if (Object.hasOwn(compositePrimaryKeys, pkName)) {
						const columns = extra.meta.columns.map((c) => c.name).join(', ');
						throw new Error(
							`"${name}" declares two primary keys that both derive the name "${pkName}" `
								+ `(the second is on "${columns}"). `
								+ 'Give at least one an explicit name.',
						);
					}
					compositePrimaryKeys[pkName] = {
						name: pkName,
						columns: extra.meta.columns.map((c) => c.name),
					};
					break;
				}
				case 'unique': {
					const uqName = uniqueConstraintName(extra.meta, name);
					if (Object.hasOwn(uniqueConstraints, uqName)) {
						const columns = extra.meta.columns.map((c) => c.name).join(', ');
						throw new Error(
							`"${name}" declares two unique constraints that both derive the name "${uqName}" `
								+ `(the second is on "${columns}"). `
								+ 'Give at least one an explicit name.',
						);
					}
					uniqueConstraints[uqName] = {
						name: uqName,
						columns: extra.meta.columns.map((c) => c.name),
						declarationOrder: tailOrder++,
					};
					break;
				}
				case 'foreignKey': {
					// The derivation is imported, not restated: the snapshot keys
					// foreign keys by this name, so a spelling that differs from the
					// DDL's — or that omits the columns, as this one did — loses a
					// constraint to a collision between two unnamed keys.
					const fkName = foreignKeyName(extra.meta, name);
					if (Object.hasOwn(foreignKeys, fkName)) {
						const columns = extra.meta.columns.map((c) => c.name).join(', ');
						throw new Error(
							`"${name}" declares two foreign keys that both derive the name "${fkName}" `
								+ `(the second is on "${columns}"). `
								+ 'Give at least one an explicit name.',
						);
					}
					foreignKeys[fkName] = {
						name: fkName,
						columns: extra.meta.columns.map((c) => c.name),
						tableTo: extra.meta.foreignColumns[0]?.tableName ?? '',
						columnsTo: extra.meta.foreignColumns.map((c) => c.name),
						onDelete: extra.meta.onDelete,
						onUpdate: extra.meta.onUpdate,
						declarationOrder: tailOrder++,
					};
					break;
				}
				case 'check': {
					// `renderInline` can throw the empty-array DDL refusal
					// (`src/ddl.ts`'s `onEmptyArrayPredicate`/`onForeignFragment`),
					// which comes back anonymous — no table or constraint name.
					// Snapshot generation runs before the diff engine's own
					// `checkDDL` call would normally attach that context, so it is
					// wrapped here through the same `withDDLContext` helper
					// `checkDDL` uses, rather than calling `renderInline` bare.
					// `isPredicate: true` matters here and not only in `checkDDL`: this is the
					// *only* place in the whole kit where a check's `SQLChunk` becomes text
					// (`generate`/`check`/`push` all render tables from the snapshot via
					// `createTableFromSnapshot`, which reads this string), so a refusal that
					// fires only in `checkDDL` never sees a migration.
					const value = withDDLContext(name, extra.meta.name, () => renderInline(extra.meta.value, true));
					if (Object.hasOwn(checkConstraints, extra.meta.name)) {
						throw new Error(
							`"${name}" declares two check constraints both named "${extra.meta.name}" `
								+ `(the second is "${value}"). `
								+ 'Rename one — check() requires an explicit name, so both already have one.',
						);
					}
					checkConstraints[extra.meta.name] = {
						name: extra.meta.name,
						value,
						declarationOrder: tailOrder++,
					};
					break;
				}
			}
		}

		const perTable = options?.byTable[name];
		result[name] = {
			name,
			columns,
			indexes,
			foreignKeys,
			compositePrimaryKeys,
			uniqueConstraints,
			checkConstraints,
			strict: perTable?.strict ?? false,
			withoutRowid: perTable?.withoutRowid ?? false,
			appendOnly: appendOnlySnapshotValue(t, perTable?.appendOnly),
		};
	}

	return { version: SNAPSHOT_VERSION, dialect: 'sqlite', id, prevId: '', tables: result, origin: 'schema' };
}

const isTableLike = (value: unknown): value is Table =>
	typeof value === 'object' && value !== null
	&& Symbol.for('ormD1:IsTable') in (value as Record<symbol, unknown>);

/** The `CREATE TABLE` a snapshot table implies, without needing live objects. */
export function createTableFromSnapshot(t: TableSnapshot): string {
	const quote = (name: string): string => `"${name.replaceAll('"', '""')}"`;
	const hasCompositePk = Object.keys(t.compositePrimaryKeys).length > 0;
	const parts: string[] = [];

	for (const column of Object.values(t.columns)) {
		let ddl = `${quote(column.name)} ${column.declaredType ?? column.type}`;
		if (column.collate) ddl += ` collate ${column.collate}`;
		if (!hasCompositePk && column.primaryKey) {
			ddl += ' primary key';
			if (column.autoincrement) ddl += ' autoincrement';
		}
		if (column.notNull) ddl += ' not null';
		if (column.unique) ddl += ' unique';
		if (column.generated) ddl += ` generated always as (${column.generated.as}) ${column.generated.mode}`;
		if (column.default !== undefined) ddl += ` default ${column.default}`;
		if (column.references) ddl += referenceClause(column.references, quote);
		parts.push(ddl);
	}

	for (const pk of Object.values(t.compositePrimaryKeys)) {
		// A member's own `collate` (`[F-115]`), same rendering as a unique
		// constraint member's just below — re-emitting it is the only way a
		// rebuild does not silently loosen a case-insensitive (or otherwise
		// non-binary) primary key back down to plain BINARY comparison.
		const members = pk.columns.map(normalizeUniqueColumn);
		// An arity-1 clause (only reachable when its lone member states a
		// non-`binary` collate — see `introspect.ts`) is still this table's
		// *only* primary key: `hasCompositePk` above suppressed the column's
		// own inline `primary key`/`autoincrement`, and this is the only other
		// place that PK gets rendered, so a rowid-alias column's
		// `AUTOINCREMENT` has to be carried across here or the rebuild loses it
		// (`introspect → rebuild → introspect` then disagrees on
		// `autoincrement`, and SQLite starts reusing deleted rowids).
		const autoincrement = members.length === 1 && t.columns[members[0]!.name]?.autoincrement === true;
		// `AUTOINCREMENT` sits *inside* the parens, after the indexed-column
		// list — `primary key ("id" collate nocase autoincrement)` — not after
		// the closing paren (that is a syntax error SQLite refuses outright).
		parts.push(
			`constraint ${quote(pk.name)} primary key (${
				members.map((c) => `${quote(c.name)}${c.collate ? ` collate ${c.collate}` : ''}`).join(', ')
			}${autoincrement ? ' autoincrement' : ''})`,
		);
	}

	// Unique / foreign-key / check constraints are interleaved in `declarationOrder`
	// (schema-origin snapshots have it on every entry; an introspected snapshot
	// leaves it `undefined` on all of them, and `??` falls each group back to its
	// own `Record`'s insertion order, exactly as before). Grouping all uniques,
	// then all foreign keys, then all checks — regardless of how they were
	// declared — only reproduced `createTable`'s interleaved output for a schema
	// that happened to declare its extras in that grouped order (`[F-103]`).
	const tail: { order: number; ddl: string }[] = [];
	Object.values(t.uniqueConstraints).forEach((uq, i) => {
		const members = uq.columns.map(normalizeUniqueColumn);
		tail.push({
			order: uq.declarationOrder ?? i,
			ddl: `constraint ${quote(uq.name)} unique (${
				members.map((c) => `${quote(c.name)}${c.collate ? ` collate ${c.collate}` : ''}`).join(', ')
			})`,
		});
	});
	Object.values(t.foreignKeys).forEach((fk, i) => {
		tail.push({
			order: fk.declarationOrder ?? i,
			ddl: `constraint ${quote(fk.name)} foreign key (${fk.columns.map(quote).join(', ')})`
				+ ` references ${quote(fk.tableTo)}(${fk.columnsTo.map(quote).join(', ')})`
				+ (fk.onDelete ? ` on delete ${fk.onDelete}` : '')
				+ (fk.onUpdate ? ` on update ${fk.onUpdate}` : ''),
		});
	});
	Object.values(t.checkConstraints).forEach((check, i) => {
		tail.push({ order: check.declarationOrder ?? i, ddl: `constraint ${quote(check.name)} check (${check.value})` });
	});
	tail.sort((a, b) => a.order - b.order);
	for (const item of tail) parts.push(item.ddl);

	// Same order as `createTable` in `orm-d1/ddl`, and the same order
	// `sqlite_master` reports back — which is what lets an introspected snapshot
	// compare equal to a schema-derived one.
	const suffix = [t.strict ? 'strict' : undefined, t.withoutRowid ? 'without rowid' : undefined]
		.filter((s) => s !== undefined);

	return `create table ${quote(t.name)} (\n${parts.map((p) => `\t${p}`).join(',\n')}\n)${
		suffix.length > 0 ? ` ${suffix.join(', ')}` : ''
	}`;
}

const referenceClause = (fk: ForeignKeySnapshot, quote: (name: string) => string): string =>
	` references ${quote(fk.tableTo)}(${quote(fk.columnsTo[0] ?? '')})`
	+ (fk.onDelete ? ` on delete ${fk.onDelete}` : '')
	+ (fk.onUpdate ? ` on update ${fk.onUpdate}` : '');

export function createIndexFromSnapshot(index: IndexSnapshot, tableName: string): string {
	const quote = (name: string): string => `"${name.replaceAll('"', '""')}"`;
	const renderColumn = (c: IndexColumnSnapshot): string => {
		const base = c.isExpression ? c.expression : quote(c.expression);
		const collate = c.collate ? ` collate ${c.collate}` : '';
		const order = c.desc ? ' desc' : '';
		return `${base}${collate}${order}`;
	};
	return `create ${index.isUnique ? 'unique ' : ''}index ${quote(index.name)} on ${quote(tableName)} (${
		index.columns.map(normalizeIndexColumn).map(renderColumn).join(', ')
	})${index.where ? ` where ${index.where}` : ''}`;
}

/**
 * The comparable form of a table.
 *
 * Two snapshots of the *same* schema do not have to be equal field for field,
 * because SQLite does not preserve everything a schema module states. It has
 * no way to report whether `unique` was written on the column or as a table
 * constraint, and it discards the declared name of a unique or foreign-key
 * constraint entirely — a `unique('post_tags_tag_unique')` comes back as
 * `sqlite_autoindex_post_tags_1`. Comparing raw snapshots therefore reported
 * drift on a database that exactly matched its schema, and `check` exited
 * non-zero forever while `push` rebuilt every table on every run.
 *
 * So comparison happens on this normalised shape instead: constraints are
 * lifted off columns to the table level, and identified by what they *do*
 * rather than by what they are called. Generation still reads the original
 * snapshot, which keeps the declared names in the emitted DDL.
 */
export interface CanonicalColumn {
	readonly type: string;
	/**
	 * The raw `declaredType` this column's `type` was derived from, when the
	 * snapshot carried one. `undefined` means this is a pre-`declaredType`
	 * snapshot (written before that field existed) — see `columnDifference`.
	 */
	readonly declaredType: string | undefined;
	readonly notNull: boolean;
	readonly default: string | null;
	readonly autoincrement: boolean;
	readonly generated: string | null;
	/**
	 * Folded to lowercase, with `binary` collapsed to `undefined` — same
	 * technique `canonicalIndex` (`diff.ts`) already applies to an index
	 * member's collation, for the same reason: D1 preserves a `COLLATE`
	 * clause's original case verbatim, so `collate NoCase` (live) and
	 * `NOCASE` (schema, hypothetically) would otherwise compare unequal.
	 * `undefined` here means "unstated or BINARY"; anything else is a real,
	 * reportable collation.
	 */
	readonly collate: string | undefined;
	/** Carried from `ColumnSnapshot.collateStated` — see there. */
	readonly collateStated: boolean;
}

/**
 * The affinity rule `columnDifference` used before `declaredType` existed: a
 * plain substring search over the five canonical spellings, defaulting to
 * `'text'`. Kept only to reproduce what an old snapshot's `type` field means,
 * so upgrading past `declaredType` does not itself look like a type change.
 */
const legacyAffinity = (declared: string): string => {
	const lower = declared.toLowerCase();
	return ['integer', 'text', 'real', 'blob', 'numeric'].find((candidate) => lower.includes(candidate)) ?? 'text';
};

/** One member of a canonicalised unique constraint — see `CanonicalTable.uniques`. */
export interface CanonicalUniqueMember {
	readonly name: string;
	readonly collate?: string;
}

export interface CanonicalTable {
	readonly columns: Record<string, CanonicalColumn>;
	/**
	 * The primary key's columns, in declared order, each with its own
	 * `collate` when it states one — a lone column-level PK never does (SQLite
	 * has no syntax for that), only a table-level `primary key (…)` clause's
	 * member can (`[F-115]`). Compared with `samePrimaryKeyMembers`, which
	 * (like `sameUniqueMembers`) exempts an unstated member collation on a
	 * schema-derived side, since the schema DSL has no way to author one.
	 */
	readonly primaryKey: readonly CanonicalUniqueMember[];
	/**
	 * One entry per table-level unique constraint, each a member list rather
	 * than a pre-serialised string — `sameUniques` needs the structure to apply
	 * the same "unexpressible in the schema DSL" exemption to a member's
	 * `collate` that `columnDifference` already applies to a column's.
	 */
	readonly uniques: readonly (readonly CanonicalUniqueMember[])[];
	readonly foreignKeys: readonly string[];
	readonly checks: readonly string[];
	/** Part of the `CREATE TABLE`, so a change here means a rebuild. */
	readonly strict: boolean;
	readonly withoutRowid: boolean;
	/**
	 * A separate trigger object; changes without touching the table.
	 * Canonicalised by `appendOnlyKey` so a column list compares as a string.
	 */
	readonly appendOnly: string;
}

/**
 * Why two canonical columns differ, in the words the migration comment uses.
 * The tuple is compared field by field rather than as a blob so the reason
 * stays as specific as it was before normalisation.
 */
export const columnDifference = (
	a: CanonicalColumn,
	b: CanonicalColumn,
	/**
	 * Whether the snapshot `b` was derived from is schema-authored. Only then
	 * is `b.collate === undefined` structurally forced rather than a genuine
	 * statement of BINARY — see the comment below.
	 */
	bIsSchemaDerived: boolean,
): string | undefined => {
	if (a.type !== b.type && !typeMatchesAcrossUpgrade(a, b) && !typeMatchesAcrossUpgrade(b, a)) return 'changes type';
	if (a.notNull !== b.notNull) return 'changes nullability';
	if (a.default !== b.default) return 'changes its default';
	if (a.autoincrement !== b.autoincrement) return 'changes autoincrement';
	if (a.generated !== b.generated) return 'changes its generated expression';
	// A live column can carry a real, non-BINARY collation that the schema DSL
	// has no way to author (Drizzle has no `.collate()`), so `after.collate` is
	// `undefined` forever on a schema-derived snapshot even when the database
	// genuinely has one. That is "unexpressible", not "changed to binary" —
	// forcing a destructive recreate on the very first `generate` after a
	// `pull` would be a permanent, unfixable false positive. `pull` reports the
	// live value instead, via `unexpressibleTableOptionWarnings`.
	//
	// The exemption is keyed on `b` actually being schema-derived — not merely
	// on `b.collate` being `undefined` — because an introspected snapshot can
	// state `undefined` two genuine ways: never mentioned, or explicitly
	// `collate binary` (folded to `undefined` above). Keying on the value alone
	// hid introspection-to-introspection drift (a hand-rebuilt production
	// table gaining a real collation the pulled baseline never had) and made
	// an explicit `collate binary` on one side permanently unreachable against
	// a real collation on the other. Only a schema-derived `b` is structurally
	// incapable of stating one; everything else — schema-to-schema,
	// introspection-to-introspection, or a schema stating one where the live
	// db states another — still needs to be caught.
	// `[F-115]`: the exemption below only applies while `b.collate` is
	// *structurally* forced to `undefined` — the DSL has no `.collate()`. Once
	// the `tableOptions()` sidecar states a column's collation (`b.collateStated`),
	// even as an explicit "none", that is a real statement of intent and a
	// live divergence from it is genuine, reportable drift.
	if (
		!(bIsSchemaDerived && !b.collateStated && a.collate !== undefined && b.collate === undefined)
		&& a.collate !== b.collate
	) {
		return 'changes its collation';
	}
	return undefined;
};

/**
 * Whether two ordered member lists are the same, member for member —
 * shared by a table-level unique constraint's members (`sameUniques`, which
 * still needs the multiset match around this for constraint-to-constraint
 * matching) and a primary key's own members (`requiresRecreate` in
 * `diff.ts`, positionally: a table has at most one primary key, so there is
 * no set of candidates to match against, only the one list to compare).
 */
export const sameUniqueMembers = (
	a: readonly CanonicalUniqueMember[],
	b: readonly CanonicalUniqueMember[],
	/** Same reading as `columnDifference`'s parameter of the same name. */
	bIsSchemaDerived: boolean,
): boolean => {
	if (a.length !== b.length) return false;
	for (let i = 0; i < a.length; i++) {
		if (a[i]!.name !== b[i]!.name) return false;
		// The same "unexpressible in the schema DSL" exemption `columnDifference`
		// applies to a column's own `collate`: the schema DSL has no `.collate()`
		// spelling at all (`docs/04`), so a unique member's collation is exactly
		// as unstateable there as a column's — a schema-derived `b` can never
		// carry one, so its absence is not "changed to binary".
		if (bIsSchemaDerived && a[i]!.collate !== undefined && b[i]!.collate === undefined) continue;
		if (a[i]!.collate !== b[i]!.collate) return false;
	}
	return true;
};

/**
 * Whether two tables' unique constraints are the same set, ignoring the
 * unexpressible-collation gap `sameUniqueMembers` already carves out.
 *
 * Constraint names are not comparable (see `canonicalFk`'s note), so this
 * matches by content — a multiset of member lists — rather than by position:
 * `a`'s constraint order has no relationship to `b`'s.
 */
export const sameUniques = (
	a: readonly (readonly CanonicalUniqueMember[])[],
	b: readonly (readonly CanonicalUniqueMember[])[],
	bIsSchemaDerived: boolean,
): boolean => {
	if (a.length !== b.length) return false;
	const remaining = b.map((members) => members);
	for (const members of a) {
		const index = remaining.findIndex((candidate) => sameUniqueMembers(members, candidate, bIsSchemaDerived));
		if (index === -1) return false;
		remaining.splice(index, 1);
	}
	return true;
};

/**
 * Whether `old` (no `declaredType`, i.e. a pre-upgrade snapshot) and `fresh`
 * (carries a `declaredType`) actually describe the same type, once `old`'s
 * value is reinterpreted under the rule that produced it.
 *
 * A pre-`declaredType` snapshot's `type` was computed with the old substring
 * rule (`legacyAffinity`), not `affinityOf`'s real SQLite rules. Comparing the
 * two rules' outputs directly disagrees for plenty of customTypes even though
 * nothing about the schema changed — e.g. `customType(() => 'int')` was
 * recorded as `'text'` under the old rule but is `'integer'` under the new
 * one. So when one side has no `declaredType`, the two only really differ if
 * applying the OLD rule to the NEW side's `declaredType` still disagrees with
 * what the old snapshot recorded.
 *
 * Both sides carrying a `declaredType` skips this entirely — that comparison
 * stays the plain `a.type !== b.type` check, so a genuine type change between
 * two current-shaped snapshots is still caught.
 */
const typeMatchesAcrossUpgrade = (old: CanonicalColumn, fresh: CanonicalColumn): boolean => {
	if (old.declaredType !== undefined || fresh.declaredType === undefined) return false;
	return legacyAffinity(fresh.declaredType) === old.type;
};

/**
 * An expression default compares without its outer parentheses.
 *
 * `CREATE TABLE` *requires* them — `default (unixepoch())` is the only legal
 * spelling — but `pragma table_info` reports the expression with them stripped.
 * So the schema said `(unixepoch())`, the database said `unixepoch()`, and the
 * one idiom D1 users reach for most drifted against itself on every `check`
 * and `push`, taking a destructive rebuild with it.
 */
const canonicalDefault = (value: string | undefined): string | null => {
	if (value === undefined) return null;
	const text = value.trim();
	if (!text.startsWith('(') || !text.endsWith(')')) return text;

	// Only when the outer pair actually wraps the whole expression: `(a) + (b)`
	// starts and ends with a paren but is not parenthesised.
	let depth = 0;
	for (let i = 0; i < text.length; i++) {
		if (text[i] === '(') depth++;
		else if (text[i] === ')') {
			depth--;
			if (depth === 0 && i < text.length - 1) return text;
		}
	}
	return canonicalDefault(text.slice(1, -1));
};

/** Constraint names are not comparable, so everything is keyed by content. */
const canonicalFk = (fk: ForeignKeySnapshot): string =>
	JSON.stringify([
		[...fk.columns],
		fk.tableTo,
		[...fk.columnsTo],
		(fk.onDelete ?? 'no action').toLowerCase(),
		(fk.onUpdate ?? 'no action').toLowerCase(),
	]);

/**
 * SQLite's declared-type → affinity rules, verbatim from the documentation.
 *
 * A live database records whatever the `CREATE TABLE` said — `VARCHAR(255)`,
 * `BOOLEAN`, `DATETIME`, `INT` — while an orm-d1 schema only ever produces the
 * five canonical spellings. To SQLite those pairs are *identical*: affinity is
 * the whole of a column's type, and `VARCHAR(255)` is `TEXT`.
 *
 * Comparing the raw strings therefore reported a type change on every column of
 * every table that orm-d1 did not create — which `pull` then turned into a
 * destructive rebuild that rewrote the live types for no benefit. Compared by
 * affinity, a pulled schema is stable, and a genuine change (`INTEGER` to
 * `TEXT`) still differs because the affinities do.
 *
 * Order matters and is part of the rule: `INT` is checked before `CHAR`, so
 * `POINT` is INTEGER, as SQLite says it is.
 */
export const typeAffinity = (declared: string): 'integer' | 'text' | 'blob' | 'real' | 'numeric' => {
	const type = declared.toUpperCase();
	if (type.includes('INT')) return 'integer';
	if (type.includes('CHAR') || type.includes('CLOB') || type.includes('TEXT')) return 'text';
	// An empty declared type is BLOB; so is anything containing BLOB.
	if (type.includes('BLOB') || type.trim() === '') return 'blob';
	if (type.includes('REAL') || type.includes('FLOA') || type.includes('DOUB')) return 'real';
	return 'numeric';
};

export const canonicalTable = (table: TableSnapshot): CanonicalTable => {
	// `Object.create(null)`, not `{}` — same hazard as `snapshotFromSchema`'s
	// own column map: a column literally named `__proto__` assigned through a
	// plain object sets the prototype instead of adding an entry, dropping it
	// from the canonical comparison `requiresRecreate` (`diff.ts`) uses to
	// decide whether a table needs rebuilding.
	const columns: Record<string, CanonicalColumn> = Object.create(null);
	const uniques: (readonly CanonicalUniqueMember[])[] = [];
	const foreignKeys: string[] = [];
	// Same member shape `uniques` uses ({ name, collate? }), in declared
	// (positional) order — a table has at most one primary key, so unlike
	// `uniques` this never needs multiset matching, only a member-for-member
	// compare. Keeping a member's `collate` here (rather than the bare name
	// `compositeColumns` below uses for the NOT-NULL identity check) is what
	// lets `requiresRecreate`'s `samePrimaryKeyMembers` notice two
	// otherwise-identical composite PKs that differ only in a member's
	// collation — before this, that difference diffed to zero statements, the
	// same gap `[F-111]` closed for `uniques`.
	const primaryKeyColumns: CanonicalUniqueMember[] = [];

	// A single-column primary key is NOT NULL whether or not anyone wrote it:
	// SQLite reports it that way, and introspection records it. Spelling the
	// key as a table-level `primaryKey({ columns: [t.id] })` left the schema
	// side saying nullable, so the table rebuilt on every run.
	const lonePrimaryKey = new Set<string>();
	const composite = Object.values(table.compositePrimaryKeys);
	// Normalised to plain names here (`[F-115]` added an optional member
	// `collate`, same shape as a unique constraint member): this identity
	// check only cares which column is the lone primary key, not how it
	// compares — a member's own `collate` is compared, if at all, where
	// `sameUniques` already knows which side is schema-derived.
	const compositeColumns = composite.flatMap((pk) => pk.columns.map(normalizeUniqueColumn)).map((c) => c.name);
	if (compositeColumns.length === 1) lonePrimaryKey.add(compositeColumns[0]!);
	for (const column of Object.values(table.columns)) {
		if (column.primaryKey) lonePrimaryKey.add(column.name);
	}

	for (const [name, column] of Object.entries(table.columns)) {
		// `unique` and `references` are dropped here and re-added below, so a
		// column-level constraint and its table-level spelling compare equal.
		columns[name] = {
			// Affinity, not the declared spelling — see `typeAffinity`.
			type: typeAffinity(column.type),
			declaredType: column.declaredType,
			notNull: column.notNull || lonePrimaryKey.has(column.name),
			default: canonicalDefault(column.default),
			autoincrement: column.autoincrement,
			generated: column.generated
				? JSON.stringify({ ...column.generated, as: column.generated.as.replaceAll(/\s+/g, ' ').trim() })
				: null,
			collate: column.collate && column.collate.toLowerCase() !== 'binary'
				? column.collate.toLowerCase()
				: undefined,
			collateStated: column.collateStated ?? false,
		};
		// A single-column table-level PK clause with an explicit member
		// `collate` is recorded in `table.compositePrimaryKeys` even at arity 1
		// (`[F-115]`'s introspection side — see `introspect.ts`), so it is
		// already in `compositeColumns` and pushed with its collation by the
		// loop below; pushing the bare name here too would duplicate it.
		if (column.primaryKey && !compositeColumns.includes(column.name)) {
			primaryKeyColumns.push({ name: column.name });
		}
		// Same shape the table-level branch below now uses ({ name, collate? }) —
		// `JSON.stringify` drops an `undefined` `collate`, so this still reads
		// identically to a plain `[{"name":"email"}]` when there is none. A
		// single-column `unique` (this branch) is reported by introspection as a
		// `uniqueConstraints` entry, not as `column.unique` (see the comment on
		// that field) — mismatched shapes here used to make an in-sync, unique
		// single column compare unequal against itself the moment the table-level
		// branch below started reporting `collate` (`[F-111]`'s own regression risk).
		if (column.unique) uniques.push([{ name: column.name }]);
		if (column.references) foreignKeys.push(canonicalFk(column.references));
	}

	for (const pk of Object.values(table.compositePrimaryKeys)) {
		primaryKeyColumns.push(
			...pk.columns.map(normalizeUniqueColumn).map((c) => (
				c.collate && c.collate.toLowerCase() !== 'binary'
					? { name: c.name, collate: c.collate.toLowerCase() }
					: { name: c.name }
			)),
		);
	}
	for (const u of Object.values(table.uniqueConstraints)) {
		// A member's own `collate` is part of the constraint's identity: two
		// otherwise-identical `unique (email)` clauses that differ only in
		// whether `email` carries `collate nocase` enforce different things, and
		// must diff (`[F-111]`) — the same `undefined`/`binary` fold `canonicalTable`
		// already applies to a column's own collation, so the schema side (which
		// never states one) and a `BINARY`-declared live one still compare equal.
		// Whether an *unstated* member collation is exempted from the comparison
		// entirely (schema DSL cannot author one, same as a column's own
		// `collate`) is `sameUniques`'s call, not this function's — it needs to
		// know which *side* is schema-derived, which a single table's snapshot
		// does not know about itself.
		uniques.push(
			u.columns.map(normalizeUniqueColumn).map((c) => ({
				name: c.name,
				...(c.collate && c.collate.toLowerCase() !== 'binary' ? { collate: c.collate.toLowerCase() } : {}),
			})),
		);
	}
	for (const fk of Object.values(table.foreignKeys)) foreignKeys.push(canonicalFk(fk));

	return {
		columns,
		primaryKey: primaryKeyColumns,
		// `pragma index_list` reports SQLite's *automatic* unique indexes (one
		// per column-level `.unique()`/table-level `unique(...)`) in reverse
		// creation order, so two semantically-identical tables — one built from
		// the schema, one introspected live, or the same live table introspected
		// twice after an unrelated rebuild — can disagree on this array's order
		// with no difference in what they actually enforce. `sameUniques` already
		// does a multiset match so it never cared, but any order-sensitive deep
		// comparison of the *whole* canonical table (`kit/test/workers/fuzz.test.ts`'s
		// `comparable()`) did. Sorting on each member list's own serialised form
		// gives a deterministic order independent of either side's constraint
		// declaration/introspection order.
		uniques: uniques.slice().sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b))),
		foreignKeys: foreignKeys.sort(),
		// SQLite keeps the check's text but not reliably its whitespace.
		checks: Object.values(table.checkConstraints)
			.map((c) => c.value.replaceAll(/\s+/g, ' ').trim())
			.sort(),
		strict: table.strict ?? false,
		withoutRowid: table.withoutRowid ?? false,
		appendOnly: appendOnlyKey(table.appendOnly),
	};
};

/** Sanity check: the snapshot must reproduce what the DDL generator emits. */
export const assertRoundTrip = (t: Table): void => {
	const snapshot = snapshotFromSchema([t]);
	const fromSnapshot = createTableFromSnapshot(snapshot.tables[getTableName(t)]!);
	const direct = createTable(t);
	if (fromSnapshot !== direct) {
		throw new Error(`Snapshot drift for "${getTableName(t)}":\n${direct}\n---\n${fromSnapshot}`);
	}
};
